package db.migration;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

/** Owns disabled Analytics raw-event and daily projection persistence. */
public class V1__analytics_schema extends BaseJavaMigration {

    private static final Set<String> EVENT_COLUMNS = Set.of(
            "id", "deduplication_key", "event_type", "event_time", "order_id", "user_id",
            "restaurant_id", "shipper_id", "amount", "order_status", "payment_method",
            "restaurant_name", "raw_payload");
    private static final Set<String> ORDER_STATS_COLUMNS = Set.of(
            "id", "stat_date", "restaurant_id", "total_orders", "delivered_orders",
            "cancelled_orders", "pending_orders", "total_revenue", "total_shipping_fee",
            "total_discount", "avg_order_value", "new_customers");
    private static final Set<String> REVENUE_STATS_COLUMNS = Set.of(
            "id", "stat_date", "restaurant_id", "total_payment_amount", "successful_payments",
            "failed_payments", "total_withdrawals", "platform_fee");

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String events = findTable(connection, "analytics_events");
        String orderStats = findTable(connection, "daily_order_stats");
        String revenueStats = findTable(connection, "daily_revenue_stats");
        int existing = (events == null ? 0 : 1) + (orderStats == null ? 0 : 1)
                + (revenueStats == null ? 0 : 1);
        if (existing == 0) {
            createTables(connection);
        } else if (existing != 3) {
            throw new FlywayException("Existing Analytics schema is incomplete: raw events and both daily stats tables must exist");
        } else {
            requireColumns(connection, events, EVENT_COLUMNS, "analytics_events");
            requireColumns(connection, orderStats, ORDER_STATS_COLUMNS, "daily_order_stats");
            requireColumns(connection, revenueStats, REVENUE_STATS_COLUMNS, "daily_revenue_stats");
        }

        requireNoDuplicateGroups(connection, "analytics_events", "deduplication_key",
                "duplicate analytics event key");
        requireNoDuplicateGroups(connection, "daily_order_stats", "stat_date, restaurant_id",
                "duplicate daily order scope");
        requireNoDuplicateGroups(connection, "daily_revenue_stats", "stat_date, restaurant_id",
                "duplicate daily revenue scope");

        addConstraintIfMissing(connection, "analytics_events", "uk_analytics_event_dedup_key",
                "UNIQUE (deduplication_key)");
        addConstraintIfMissing(connection, "daily_order_stats", "uk_daily_order_stats_scope",
                "UNIQUE NULLS NOT DISTINCT (stat_date, restaurant_id)");
        addConstraintIfMissing(connection, "daily_revenue_stats", "uk_daily_revenue_stats_scope",
                "UNIQUE NULLS NOT DISTINCT (stat_date, restaurant_id)");
        createIndexes(connection);
    }

    private void createTables(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE analytics_events (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    deduplication_key VARCHAR(160) NOT NULL, event_type VARCHAR(50) NOT NULL,
                    event_time TIMESTAMP NOT NULL, order_id BIGINT, user_id BIGINT,
                    restaurant_id BIGINT, shipper_id BIGINT, amount DECIMAL(15,2),
                    order_status VARCHAR(30), payment_method VARCHAR(30),
                    restaurant_name VARCHAR(255), raw_payload TEXT
                )
                """);
        execute(connection, """
                CREATE TABLE daily_order_stats (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    stat_date DATE NOT NULL, restaurant_id BIGINT,
                    total_orders BIGINT NOT NULL, delivered_orders BIGINT NOT NULL,
                    cancelled_orders BIGINT NOT NULL, pending_orders BIGINT NOT NULL,
                    total_revenue DECIMAL(15,2), total_shipping_fee DECIMAL(15,2),
                    total_discount DECIMAL(15,2), avg_order_value DECIMAL(12,2),
                    new_customers BIGINT NOT NULL
                )
                """);
        execute(connection, """
                CREATE TABLE daily_revenue_stats (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    stat_date DATE NOT NULL, restaurant_id BIGINT,
                    total_payment_amount DECIMAL(15,2), successful_payments BIGINT NOT NULL,
                    failed_payments BIGINT NOT NULL, total_withdrawals DECIMAL(15,2),
                    platform_fee DECIMAL(15,2)
                )
                """);
    }

    private void createIndexes(Connection connection) throws SQLException {
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_event_type_time ON analytics_events (event_type, event_time)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_restaurant_id ON analytics_events (restaurant_id)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_event_time ON analytics_events (event_time)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_daily_order_date ON daily_order_stats (stat_date)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_daily_revenue_date ON daily_revenue_stats (stat_date)");
    }

    private void requireNoDuplicateGroups(Connection connection, String table, String columns,
                                          String label) throws SQLException {
        long groups = queryCount(connection, "SELECT count(*) FROM (SELECT " + columns + " FROM "
                + table + " GROUP BY " + columns + " HAVING count(*) > 1) duplicates");
        if (groups > 0) {
            throw new FlywayException("Analytics schema contains " + groups + " " + label
                    + " group(s); manual reconciliation is required");
        }
    }

    private void addConstraintIfMissing(Connection connection, String table, String constraint,
                                        String definition) throws SQLException {
        if (!hasIndexNamedLike(connection, table, constraint)) {
            execute(connection, "ALTER TABLE " + table + " ADD CONSTRAINT " + constraint + " " + definition);
        }
    }

    private boolean hasIndexNamedLike(Connection connection, String table, String expected) throws SQLException {
        try (ResultSet indexes = connection.getMetaData().getIndexInfo(
                null, connection.getSchema(), table, true, false)) {
            while (indexes.next()) {
                String name = indexes.getString("INDEX_NAME");
                if (name != null && name.toLowerCase(Locale.ROOT).startsWith(expected.toLowerCase(Locale.ROOT))) {
                    return true;
                }
            }
        }
        return false;
    }

    private void requireColumns(Connection connection, String tableName, Set<String> required,
                                String logicalName) throws SQLException {
        Set<String> columns = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData()
                .getColumns(null, connection.getSchema(), tableName, "%")) {
            while (resultSet.next()) columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
        }
        Set<String> missing = new HashSet<>(required);
        missing.removeAll(columns);
        if (!missing.isEmpty()) {
            throw new FlywayException("Existing " + logicalName + " table is missing core column(s): " + missing);
        }
    }

    private long queryCount(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement(); ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private String findTable(Connection connection, String expectedName) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(null, connection.getSchema(), "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String name = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(name)) return name;
            }
        }
        return null;
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
