package db.migration;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

/** Owns the Order aggregate schema previously created and mutated by Hibernate update. */
public class V4__order_core_schema extends BaseJavaMigration {

    private static final Set<String> ORDER_COLUMNS = Set.of(
            "id", "user_id", "restaurant_id", "shipper_id", "subtotal_price",
            "discount_amount", "shipping_fee", "total_price", "status", "payment_method",
            "delivery_address", "delivery_lat", "delivery_lng", "pickup_lat", "pickup_lng",
            "restaurant_name", "restaurant_address", "restaurant_phone", "customer_name",
            "customer_phone", "notes", "cancel_reason", "cancelled_by", "created_at",
            "updated_at", "creator_id");
    private static final Set<String> ITEM_COLUMNS = Set.of(
            "id", "order_id", "menu_item_id", "flash_sale_item_id", "menu_item_name",
            "quantity", "price", "notes");

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String orders = findTable(connection, "orders");
        String items = findTable(connection, "order_items");

        if (orders == null && items == null) {
            createCoreTables(connection);
        } else if (orders == null || items == null) {
            throw new FlywayException("Existing Order schema is incomplete: orders and order_items must both exist");
        } else {
            addNullableColumnIfMissing(connection, items, "flash_sale_item_id", "flash_sale_item_id BIGINT");
            requireColumns(connection, orders, ORDER_COLUMNS, "orders");
            requireColumns(connection, items, ITEM_COLUMNS, "order_items");
        }

        createQueryIndexes(connection);
    }

    private void createCoreTables(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE orders (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    restaurant_id BIGINT NOT NULL,
                    shipper_id BIGINT,
                    subtotal_price DECIMAL(12,2),
                    discount_amount DECIMAL(12,2),
                    shipping_fee DECIMAL(12,2),
                    total_price DECIMAL(12,2),
                    status VARCHAR(32) NOT NULL,
                    payment_method VARCHAR(255),
                    delivery_address TEXT,
                    delivery_lat DOUBLE PRECISION,
                    delivery_lng DOUBLE PRECISION,
                    pickup_lat DOUBLE PRECISION,
                    pickup_lng DOUBLE PRECISION,
                    restaurant_name VARCHAR(255),
                    restaurant_address VARCHAR(255),
                    restaurant_phone VARCHAR(255),
                    customer_name VARCHAR(255),
                    customer_phone VARCHAR(255),
                    notes TEXT,
                    cancel_reason TEXT,
                    cancelled_by BIGINT,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    creator_id BIGINT NOT NULL
                )
                """);
        execute(connection, """
                CREATE TABLE order_items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    order_id BIGINT NOT NULL,
                    menu_item_id BIGINT NOT NULL,
                    flash_sale_item_id BIGINT,
                    menu_item_name VARCHAR(255) NOT NULL,
                    quantity INTEGER NOT NULL,
                    price DECIMAL(12,2) NOT NULL,
                    notes VARCHAR(255),
                    CONSTRAINT fk_order_items_order
                        FOREIGN KEY (order_id) REFERENCES orders (id)
                )
                """);
    }

    private void createQueryIndexes(Connection connection) throws SQLException {
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_orders_user_created ON orders (user_id, created_at)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_orders_restaurant_created ON orders (restaurant_id, created_at)");
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_orders_restaurant_creator_created
                ON orders (restaurant_id, creator_id, created_at)
                """);
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_orders_shipper_created ON orders (shipper_id, created_at)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_orders_status_created ON orders (status, created_at)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_orders_creator_created ON orders (creator_id, created_at)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id)");
    }

    private void requireColumns(Connection connection, String tableName, Set<String> required,
                                String logicalName) throws SQLException {
        Set<String> columns = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData().getColumns(null, null, tableName, "%")) {
            while (resultSet.next()) {
                columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
            }
        }
        Set<String> missing = new HashSet<>(required);
        missing.removeAll(columns);
        if (!missing.isEmpty()) {
            throw new FlywayException("Existing " + logicalName + " table is missing core column(s): " + missing);
        }
    }

    private void addNullableColumnIfMissing(Connection connection, String tableName, String columnName,
                                            String definition) throws SQLException {
        Set<String> columns = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData().getColumns(null, null, tableName, "%")) {
            while (resultSet.next()) {
                columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
            }
        }
        if (!columns.contains(columnName.toLowerCase(Locale.ROOT))) {
            execute(connection, "ALTER TABLE " + tableName + " ADD COLUMN " + definition);
        }
    }

    private String findTable(Connection connection, String expectedName) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(null, null, "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(tableName)) {
                    return tableName;
                }
            }
        }
        return null;
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
