# Application Configuration
spring.application.name=notification-service
server.port=8087

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_service_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000
spring.data.redis.database=0

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.use-type-info-headers=false


# Firebase Configuration (set via environment variables)
firebase.service-account-key-path=${FIREBASE_SERVICE_ACCOUNT_KEY_PATH:classpath:firebase-service-account.json}

# WebSocket Configuration
websocket.allowed-origins=http://localhost:3000,http://localhost:8080

# Logging
logging.level.com.delivery.notification_service=DEBUG
logging.level.org.springframework.kafka=INFO

logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.web.socket.messaging=DEBUG
logging.level.org.springframework.messaging.simp=DEBUG
logging.level.org.springframework.messaging.support=DEBUG