package com.delivery.flashsale_service.migration;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.MigrationVersion;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class FlashSaleFlywayMigrationTest {

    @Test
    void cleanSchemaCreatesCampaignItemAndQueryIndexes() throws Exception {
        String url = databaseUrl("clean");
        migrate(url);
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            long campaignId = insertCampaign(statement);
            insertItem(statement, campaignId);
            assertThat(count(statement, "SELECT count(*) FROM flash_sale_items")).isEqualTo(1);
            assertThat(indexExists(connection, "idx_flash_campaign_status_start")).isTrue();
            assertThat(indexExists(connection, "idx_flash_items_campaign_status")).isTrue();
        }
    }

    @Test
    void legacySchemaPreservesCampaignAndItem() throws Exception {
        String url = databaseUrl("legacy");
        createLegacySchema(url, false, false);
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            long campaignId = insertCampaign(statement);
            insertItem(statement, campaignId);
        }
        migrate(url);
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            assertThat(count(statement, "SELECT count(*) FROM flash_sale_campaigns")).isEqualTo(1);
            assertThat(count(statement, "SELECT count(*) FROM flash_sale_items")).isEqualTo(1);
        }
    }

    @Test
    void missingCoreColumnStopsMigration() throws Exception {
        String url = databaseUrl("missing_core");
        createLegacySchema(url, true, false);
        assertThatThrownBy(() -> migrate(url)).isInstanceOf(FlywayException.class).rootCause()
                .hasMessageContaining("missing core column").hasMessageContaining("sold_quantity");
    }

    @Test
    void incompleteLegacyTablePairStopsMigration() throws Exception {
        String url = databaseUrl("incomplete");
        createLegacySchema(url, false, true);
        assertThatThrownBy(() -> migrate(url)).isInstanceOf(FlywayException.class).rootCause()
                .hasMessageContaining("schema is incomplete");
    }

    private void migrate(String url) {
        Flyway.configure().dataSource(url, "sa", "")
                .baselineOnMigrate(true).baselineVersion(MigrationVersion.fromVersion("0"))
                .load().migrate();
    }

    private void createLegacySchema(String url, boolean omitSold, boolean omitItems) throws Exception {
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE flash_sale_campaigns (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL, is_recurring BOOLEAN NOT NULL,
                        start_time TIME NOT NULL, end_time TIME NOT NULL, status VARCHAR(255) NOT NULL,
                        admin_id BIGINT, created_at TIMESTAMP, updated_at TIMESTAMP
                    )
                    """);
            if (!omitItems) {
                statement.execute("""
                        CREATE TABLE flash_sale_items (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            campaign_id BIGINT NOT NULL, restaurant_id BIGINT NOT NULL,
                            menu_item_id BIGINT NOT NULL, original_price DECIMAL(38,2) NOT NULL,
                            flash_sale_price DECIMAL(38,2) NOT NULL, stock_quantity INTEGER NOT NULL,
                            %s
                            status VARCHAR(255) NOT NULL, created_at TIMESTAMP, updated_at TIMESTAMP
                        )
                        """.formatted(omitSold ? "" : "sold_quantity INTEGER NOT NULL,"));
            }
        }
    }

    private long insertCampaign(Statement statement) throws Exception {
        statement.executeUpdate("""
                INSERT INTO flash_sale_campaigns
                    (name, is_recurring, start_time, end_time, status, created_at, updated_at)
                VALUES ('Lunch', true, '11:00:00', '13:00:00', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """, Statement.RETURN_GENERATED_KEYS);
        try (ResultSet keys = statement.getGeneratedKeys()) {
            assertThat(keys.next()).isTrue();
            return keys.getLong(1);
        }
    }

    private void insertItem(Statement statement, long campaignId) throws Exception {
        statement.executeUpdate("""
                INSERT INTO flash_sale_items
                    (campaign_id, restaurant_id, menu_item_id, original_price, flash_sale_price,
                     stock_quantity, sold_quantity, status, created_at, updated_at)
                VALUES (%d, 20, 30, 100000, 50000, 10, 0, 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """.formatted(campaignId));
    }

    private boolean indexExists(Connection connection, String expectedName) throws Exception {
        for (String table : new String[]{"flash_sale_campaigns", "flash_sale_items"}) {
            try (ResultSet indexes = connection.getMetaData().getIndexInfo(
                    null, connection.getSchema(), table, false, false)) {
                while (indexes.next()) {
                    String name = indexes.getString("INDEX_NAME");
                    if (name != null && expectedName.equalsIgnoreCase(name)) return true;
                }
            }
        }
        return false;
    }

    private long count(Statement statement, String sql) throws Exception {
        try (ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private String databaseUrl(String label) {
        return "jdbc:h2:mem:flash_sale_migration_" + label + "_" + UUID.randomUUID()
                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";
    }
}
