# Service name và port
spring.application.name=shipper-service
server.port=8086

# Database configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/shipper_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security logging (for debugging)
logging.level.org.springframework.security=DEBUG
