package com.delivery.notification_service.migration;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.MigrationVersion;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class NotificationFlywayMigrationTest {

    @Test
    void cleanSchemaCreatesTableIndexesAndUniqueDedupBoundary() throws Exception {
        String url = databaseUrl("clean");
        migrate(url);

        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            insertNotification(statement, 10, "event:1");
            assertThatThrownBy(() -> insertNotification(statement, 11, "event:1"))
                    .isInstanceOf(Exception.class)
                    .hasMessageContaining("Unique");
            assertThat(indexExists(connection, "idx_notifications_user_created")).isTrue();
            assertThat(indexExists(connection, "idx_notifications_user_read_created")).isTrue();
        }
    }

    @Test
    void legacySchemaAddsCompatibilityColumnsAndPreservesRows() throws Exception {
        String url = databaseUrl("legacy");
        createLegacyTable(url, false, false);
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            insertLegacyNotification(statement, 10);
        }

        migrate(url);

        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            assertThat(count(statement, "SELECT count(*) FROM notifications")).isEqualTo(1);
            assertThat(columnExists(connection, "creator_id")).isTrue();
            assertThat(columnExists(connection, "deduplication_key")).isTrue();
        }
    }

    @Test
    void duplicateDeduplicationKeysStopMigration() throws Exception {
        String url = databaseUrl("duplicate");
        createLegacyTable(url, true, false);
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            insertNotification(statement, 10, "event:duplicate");
            insertNotification(statement, 11, "event:duplicate");
        }

        assertThatThrownBy(() -> migrate(url))
                .isInstanceOf(FlywayException.class)
                .rootCause()
                .hasMessageContaining("duplicate deduplication key");
    }

    @Test
    void missingCoreColumnStopsMigrationInsteadOfGuessingData() throws Exception {
        String url = databaseUrl("missing_core");
        createLegacyTable(url, true, true);

        assertThatThrownBy(() -> migrate(url))
                .isInstanceOf(FlywayException.class)
                .rootCause()
                .hasMessageContaining("missing core column")
                .hasMessageContaining("status");
    }

    private void migrate(String url) {
        Flyway.configure()
                .dataSource(url, "sa", "")
                .baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("0"))
                .load()
                .migrate();
    }

    private void createLegacyTable(String url, boolean includeCompatibilityColumns, boolean omitStatus)
            throws Exception {
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE notifications (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        title VARCHAR(255) NOT NULL,
                        message TEXT NOT NULL,
                        type VARCHAR(255) NOT NULL,
                        priority VARCHAR(255),
                        %s
                        is_read BOOLEAN,
                        related_entity_id BIGINT,
                        related_entity_type VARCHAR(255),
                        data TEXT,
                        sent_at TIMESTAMP,
                        read_at TIMESTAMP,
                        created_at TIMESTAMP,
                        updated_at TIMESTAMP
                        %s
                    )
                    """.formatted(
                    omitStatus ? "" : "status VARCHAR(255),",
                    includeCompatibilityColumns
                            ? ", creator_id BIGINT, deduplication_key VARCHAR(200)"
                            : ""));
        }
    }

    private void insertNotification(Statement statement, long userId, String deduplicationKey)
            throws Exception {
        statement.executeUpdate("""
                INSERT INTO notifications
                    (user_id, title, message, type, priority, status, is_read,
                     created_at, updated_at, deduplication_key)
                VALUES (%d, 'Title', 'Message', 'ORDER_CREATED', 'MEDIUM', 'PENDING', false,
                        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '%s')
                """.formatted(userId, deduplicationKey));
    }

    private void insertLegacyNotification(Statement statement, long userId) throws Exception {
        statement.executeUpdate("""
                INSERT INTO notifications
                    (user_id, title, message, type, priority, status, is_read, created_at, updated_at)
                VALUES (%d, 'Title', 'Message', 'ORDER_CREATED', 'MEDIUM', 'PENDING', false,
                        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """.formatted(userId));
    }

    private boolean indexExists(Connection connection, String expectedName) throws Exception {
        try (ResultSet indexes = connection.getMetaData()
                .getIndexInfo(null, null, "notifications", false, false)) {
            while (indexes.next()) {
                String name = indexes.getString("INDEX_NAME");
                if (name != null && expectedName.equalsIgnoreCase(name)) {
                    return true;
                }
            }
        }
        return false;
    }

    private boolean columnExists(Connection connection, String expectedName) throws Exception {
        try (ResultSet columns = connection.getMetaData()
                .getColumns(null, null, "notifications", "%")) {
            while (columns.next()) {
                if (expectedName.equalsIgnoreCase(columns.getString("COLUMN_NAME"))) {
                    return true;
                }
            }
        }
        return false;
    }

    private long count(Statement statement, String sql) throws Exception {
        try (ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private String databaseUrl(String label) {
        return "jdbc:h2:mem:notification_migration_" + label + "_" + UUID.randomUUID()
                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";
    }
}
