{
  "apiVersion": "v1",
  "kind": "ServiceAccount",
  "metadata": {
    "name": "auth-service",
    "labels": {
      "app.kubernetes.io/name": "auth-service",
      "app.kubernetes.io/part-of": "delivery-platform",
      "app.kubernetes.io/component": "application",
      "delivery.platform/template": "provider-neutral",
      "delivery.platform/wave": "auth"
    }
  },
  "automountServiceAccountToken": false
}
