{
  "apiVersion": "v1",
  "kind": "ServiceAccount",
  "metadata": {
    "name": "config-server",
    "labels": {
      "app.kubernetes.io/name": "config-server",
      "app.kubernetes.io/part-of": "delivery-platform",
      "app.kubernetes.io/component": "control-plane",
      "delivery.platform/template": "provider-neutral",
      "delivery.platform/wave": "control"
    }
  },
  "automountServiceAccountToken": false
}
