{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "discovery-server",
    "labels": {
      "app.kubernetes.io/name": "discovery-server",
      "app.kubernetes.io/part-of": "delivery-platform",
      "app.kubernetes.io/component": "control-plane",
      "delivery.platform/template": "provider-neutral",
      "delivery.platform/wave": "control"
    }
  },
  "spec": {
    "type": "ClusterIP",
    "selector": {
      "app.kubernetes.io/name": "discovery-server"
    },
    "ports": [
      {
        "name": "http",
        "port": 8761,
        "targetPort": "http",
        "protocol": "TCP"
      },
      {
        "name": "management",
        "port": 9090,
        "targetPort": "management",
        "protocol": "TCP"
      }
    ]
  }
}
