apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - discovery-server.deployment.yaml
  - discovery-server.service.yaml
  - discovery-server.serviceaccount.yaml
  - config-server.deployment.yaml
  - config-server.service.yaml
  - config-server.serviceaccount.yaml
  - api-gateway.deployment.yaml
  - api-gateway.service.yaml
  - api-gateway.serviceaccount.yaml
  - auth-service.deployment.yaml
  - auth-service.service.yaml
  - auth-service.serviceaccount.yaml
  - user-service.deployment.yaml
  - user-service.service.yaml
  - user-service.serviceaccount.yaml
  - restaurant-service.deployment.yaml
  - restaurant-service.service.yaml
  - restaurant-service.serviceaccount.yaml
  - order-service.deployment.yaml
  - order-service.service.yaml
  - order-service.serviceaccount.yaml
  - delivery-service.deployment.yaml
  - delivery-service.service.yaml
  - delivery-service.serviceaccount.yaml
  - search-service.deployment.yaml
  - search-service.service.yaml
  - search-service.serviceaccount.yaml
  - shipper-service.deployment.yaml
  - shipper-service.service.yaml
  - shipper-service.serviceaccount.yaml
  - settlement-service.deployment.yaml
  - settlement-service.service.yaml
  - settlement-service.serviceaccount.yaml
  - notification-service.deployment.yaml
  - notification-service.service.yaml
  - notification-service.serviceaccount.yaml
  - match-service.deployment.yaml
  - match-service.service.yaml
  - match-service.serviceaccount.yaml
  - tracking-service.deployment.yaml
  - tracking-service.service.yaml
  - tracking-service.serviceaccount.yaml
  - livestream-service.deployment.yaml
  - livestream-service.service.yaml
  - livestream-service.serviceaccount.yaml
  - saga-orchestrator-service.deployment.yaml
  - saga-orchestrator-service.service.yaml
  - saga-orchestrator-service.serviceaccount.yaml
  - promotion-service.deployment.yaml
  - promotion-service.service.yaml
  - promotion-service.serviceaccount.yaml
  - analytics-service.deployment.yaml
  - analytics-service.service.yaml
  - analytics-service.serviceaccount.yaml
  - flashsale-service.deployment.yaml
  - flashsale-service.service.yaml
  - flashsale-service.serviceaccount.yaml
