CREATE TABLE IF NOT EXISTS catalog_lifecycle_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(32) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    action VARCHAR(32) NOT NULL,
    actor_principal_id BIGINT NOT NULL,
    actor_role VARCHAR(32) NOT NULL,
    before_status VARCHAR(32) NOT NULL,
    after_status VARCHAR(32) NOT NULL,
    before_version BIGINT NOT NULL,
    after_version BIGINT NOT NULL,
    correlation_id VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_catalog_lifecycle_audit_aggregate
    ON catalog_lifecycle_audits (aggregate_type, aggregate_id, occurred_at);
