CREATE TABLE IF NOT EXISTS restaurant_order_decisions (
    order_id BIGINT PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    decision VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_restaurant_order_decision CHECK (decision IN ('CONFIRMED', 'REJECTED'))
);

CREATE TABLE IF NOT EXISTS restaurant_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    event_key VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(16) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP NULL,
    last_error VARCHAR(2000) NULL,
    CONSTRAINT uk_restaurant_outbox_event_id UNIQUE (event_id),
    CONSTRAINT ck_restaurant_outbox_status CHECK (status IN ('PENDING', 'SENT', 'DEAD'))
);

CREATE INDEX IF NOT EXISTS idx_restaurant_outbox_pending
    ON restaurant_outbox_events (status, next_attempt_at, created_at);
CREATE INDEX IF NOT EXISTS idx_restaurant_outbox_order
    ON restaurant_outbox_events (aggregate_id, created_at);
