CREATE TABLE IF NOT EXISTS restaurant_serviceability_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    polygon_geo_json TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    revision BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_serviceability_zone_restaurant
        FOREIGN KEY (restaurant_id) REFERENCES restaurant (id),
    CONSTRAINT ck_serviceability_zone_priority
        CHECK (priority BETWEEN -10000 AND 10000),
    CONSTRAINT ck_serviceability_zone_revision
        CHECK (revision >= 0)
);

CREATE INDEX IF NOT EXISTS idx_serviceability_zone_restaurant_order
    ON restaurant_serviceability_zones (restaurant_id, active, priority DESC, id ASC);
