CREATE TABLE IF NOT EXISTS menu_item_inventory (
    menu_item_id BIGINT PRIMARY KEY,
    on_hand_quantity INTEGER NOT NULL DEFAULT 0,
    reserved_quantity INTEGER NOT NULL DEFAULT 0,
    revision BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_menu_item_inventory_item
        FOREIGN KEY (menu_item_id) REFERENCES menu_item (id),
    CONSTRAINT ck_menu_item_inventory_on_hand
        CHECK (on_hand_quantity >= 0),
    CONSTRAINT ck_menu_item_inventory_reserved
        CHECK (reserved_quantity >= 0 AND reserved_quantity <= on_hand_quantity),
    CONSTRAINT ck_menu_item_inventory_revision
        CHECK (revision >= 0)
);

CREATE INDEX IF NOT EXISTS idx_menu_item_inventory_revision
    ON menu_item_inventory (revision, menu_item_id);

CREATE TABLE IF NOT EXISTS menu_item_inventory_reservations (
    reservation_id UUID PRIMARY KEY,
    order_id BIGINT NOT NULL,
    user_id BIGINT,
    user_principal_id BIGINT,
    restaurant_id BIGINT NOT NULL,
    state VARCHAR(16) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_menu_inventory_reservation_order UNIQUE (order_id),
    CONSTRAINT ck_menu_inventory_reservation_state
        CHECK (state IN ('RESERVED', 'COMMITTED', 'RELEASED', 'EXPIRED'))
);

CREATE INDEX IF NOT EXISTS idx_menu_inventory_reservation_expiry
    ON menu_item_inventory_reservations (state, expires_at);

CREATE TABLE IF NOT EXISTS menu_item_inventory_reservation_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id UUID NOT NULL,
    menu_item_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_menu_inventory_line_reservation
        FOREIGN KEY (reservation_id) REFERENCES menu_item_inventory_reservations (reservation_id),
    CONSTRAINT fk_menu_inventory_line_item
        FOREIGN KEY (menu_item_id) REFERENCES menu_item (id),
    CONSTRAINT uk_menu_inventory_line_item
        UNIQUE (reservation_id, menu_item_id),
    CONSTRAINT ck_menu_inventory_line_quantity
        CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_menu_inventory_line_item
    ON menu_item_inventory_reservation_lines (menu_item_id);

CREATE TABLE IF NOT EXISTS menu_item_inventory_order_receipts (
    event_id UUID PRIMARY KEY,
    source_topic VARCHAR(255) NOT NULL,
    action VARCHAR(16) NOT NULL,
    order_id BIGINT NOT NULL,
    reservation_id UUID,
    payload_fingerprint VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_menu_inventory_receipt_action
        CHECK (action IN ('COMMIT', 'RELEASE'))
);

CREATE INDEX IF NOT EXISTS idx_menu_inventory_receipt_order
    ON menu_item_inventory_order_receipts (order_id, created_at);
