services:
  api-gateway:
    environment:
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt-public.pem
    volumes:
      - type: bind
        source: ./api-gateway/src/main/resources/public.pem
        target: /run/secrets/jwt-public.pem
        read_only: true

  auth-service:
    environment:
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt-private.pem
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt-public.pem
    volumes:
      - type: bind
        source: ./auth-service/src/main/resources/private.pem
        target: /run/secrets/jwt-private.pem
        read_only: true
      - type: bind
        source: ./auth-service/src/main/resources/public.pem
        target: /run/secrets/jwt-public.pem
        read_only: true
