# Tắt kiểm tra compatibility giữa Spring Boot & Spring Cloud
spring.cloud.compatibility-verifier.enabled=false

# Cổng cho gateway
server.port=8079
spring.application.name=api-gateway

# Cấu hình định tuyến cho AUTH-SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2

# Cấu hình định tuyến cho USER-SERVICE
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=http://localhost:8084
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=2
