# Tắt kiểm tra compatibility giữa Spring Boot & Spring Cloud
spring.cloud.compatibility-verifier.enabled=false

# Cổng cho gateway
server.port=8080
spring.application.name=api-gateway

# Cấu hình route tạm thời (nếu chưa dùng Eureka)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=http://localhost:8084
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
