ALTER TABLE vouchers ADD COLUMN IF NOT EXISTS voucher_layer VARCHAR(32);
ALTER TABLE vouchers ADD COLUMN IF NOT EXISTS funding_source VARCHAR(32);
ALTER TABLE vouchers ADD COLUMN IF NOT EXISTS approval_status VARCHAR(32);
ALTER TABLE vouchers ADD COLUMN IF NOT EXISTS owner_principal_id BIGINT;
ALTER TABLE vouchers ADD COLUMN IF NOT EXISTS restaurant_id BIGINT;
ALTER TABLE vouchers ADD COLUMN IF NOT EXISTS approved_by_principal_id BIGINT;
ALTER TABLE vouchers ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE vouchers ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(255);

UPDATE vouchers SET approval_status = 'APPROVED' WHERE approval_status IS NULL;

ALTER TABLE user_vouchers ADD COLUMN IF NOT EXISTS used_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user_vouchers ADD COLUMN IF NOT EXISTS reserved_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user_vouchers ADD COLUMN IF NOT EXISTS collected_at TIMESTAMP;
UPDATE user_vouchers SET collected_at = COALESCE(collected_at, created_at) WHERE collected_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_vouchers_layer_status_scope
    ON vouchers (voucher_layer, approval_status, scope_type, scope_ref_id, end_time);
CREATE INDEX IF NOT EXISTS idx_user_vouchers_usage
    ON user_vouchers (user_id, voucher_id, used_count, reserved_count);

CREATE TABLE IF NOT EXISTS promotion_reservations (
    reservation_id UUID PRIMARY KEY,
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    user_principal_id BIGINT,
    restaurant_id BIGINT NOT NULL,
    subtotal DECIMAL(38,2) NOT NULL,
    gross_shipping_fee DECIMAL(38,2) NOT NULL,
    item_discount DECIMAL(38,2) NOT NULL,
    shipping_discount DECIMAL(38,2) NOT NULL,
    total_discount DECIMAL(38,2) NOT NULL,
    customer_shipping_fee DECIMAL(38,2) NOT NULL,
    state VARCHAR(16) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_promotion_reservation_order UNIQUE (order_id),
    CONSTRAINT ck_promotion_reservation_state
        CHECK (state IN ('RESERVED', 'COMMITTED', 'RELEASED', 'EXPIRED')),
    CONSTRAINT ck_promotion_reservation_amounts
        CHECK (subtotal >= 0 AND gross_shipping_fee >= 0 AND item_discount >= 0
            AND shipping_discount >= 0 AND total_discount >= 0 AND customer_shipping_fee >= 0)
);

CREATE INDEX IF NOT EXISTS idx_promotion_reservation_expiry
    ON promotion_reservations (state, expires_at);

CREATE TABLE IF NOT EXISTS promotion_reservation_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id UUID NOT NULL,
    voucher_id BIGINT NOT NULL,
    voucher_code VARCHAR(50) NOT NULL,
    layer VARCHAR(32) NOT NULL,
    funding_source VARCHAR(32) NOT NULL,
    discount_base DECIMAL(38,2) NOT NULL,
    discount_amount DECIMAL(38,2) NOT NULL,
    state VARCHAR(16) NOT NULL,
    CONSTRAINT fk_promotion_reservation_line_parent
        FOREIGN KEY (reservation_id) REFERENCES promotion_reservations (reservation_id),
    CONSTRAINT fk_promotion_reservation_line_voucher
        FOREIGN KEY (voucher_id) REFERENCES vouchers (id),
    CONSTRAINT uk_promotion_reservation_line_voucher
        UNIQUE (reservation_id, voucher_id),
    CONSTRAINT ck_promotion_reservation_line_state
        CHECK (state IN ('RESERVED', 'COMMITTED', 'RELEASED', 'EXPIRED')),
    CONSTRAINT ck_promotion_reservation_line_amounts
        CHECK (discount_base >= 0 AND discount_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_promotion_reservation_line_voucher
    ON promotion_reservation_lines (voucher_id, state);
