package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

public class V2__simulation_run_journal extends BaseJavaMigration {
    @Override public void migrate(Context context) throws Exception {
        try (var s = context.getConnection().createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS simulation_run_journal (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, run_id UUID NOT NULL, recorded_at TIMESTAMP WITH TIME ZONE NOT NULL, source VARCHAR(64) NOT NULL, title VARCHAR(160) NOT NULL, payload_json TEXT NOT NULL)");
            s.execute("CREATE INDEX IF NOT EXISTS idx_simulation_run_journal_run ON simulation_run_journal (run_id, id)");
        }
    }
}
