package com.delivery.restaurant_service.migration;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.MigrationVersion;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class RestaurantFlywayMigrationTest {

    @Test
    void cleanSchemaCreatesCatalogRatingsAndQueryIndexes() throws Exception {
        String url = databaseUrl("clean");
        migrate(url);

        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            long restaurantId = insertRestaurant(statement, 10);
            insertMenuItem(statement, restaurantId);
            insertRating(statement, restaurantId, 100);
            assertThat(count(statement, "SELECT count(*) FROM menu_item")).isEqualTo(1);
            assertThat(count(statement, "SELECT count(*) FROM restaurant_ratings")).isEqualTo(1);
            assertThat(indexExists(connection, "idx_restaurant_creator")).isTrue();
            assertThat(indexExists(connection, "idx_menu_restaurant_status")).isTrue();
            assertThat(indexExists(connection, "idx_restaurant_ratings_restaurant_status")).isTrue();
        }
    }

    @Test
    void legacySchemaPreservesCatalogAndRatingRows() throws Exception {
        String url = databaseUrl("legacy");
        createLegacySchema(url, false, false);
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            long restaurantId = insertRestaurant(statement, 10);
            insertMenuItem(statement, restaurantId);
            insertRating(statement, restaurantId, 100);
        }

        migrate(url);

        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            assertThat(count(statement, "SELECT count(*) FROM restaurant")).isEqualTo(1);
            assertThat(count(statement, "SELECT count(*) FROM menu_item")).isEqualTo(1);
            assertThat(count(statement, "SELECT count(*) FROM restaurant_ratings")).isEqualTo(1);
        }
    }

    @Test
    void missingCoreColumnStopsMigrationInsteadOfGuessingRatingState() throws Exception {
        String url = databaseUrl("missing_core");
        createLegacySchema(url, true, false);

        assertThatThrownBy(() -> migrate(url))
                .isInstanceOf(FlywayException.class)
                .rootCause()
                .hasMessageContaining("missing core column")
                .hasMessageContaining("status");
    }

    @Test
    void incompleteLegacyTableSetStopsMigration() throws Exception {
        String url = databaseUrl("incomplete");
        createLegacySchema(url, false, true);

        assertThatThrownBy(() -> migrate(url))
                .isInstanceOf(FlywayException.class)
                .rootCause()
                .hasMessageContaining("schema is incomplete");
    }

    private void migrate(String url) {
        Flyway.configure()
                .dataSource(url, "sa", "")
                .baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("0"))
                .load()
                .migrate();
    }

    private void createLegacySchema(String url, boolean omitRatingStatus, boolean omitRatings)
            throws Exception {
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE restaurant (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        address TEXT,
                        description TEXT,
                        phone VARCHAR(20),
                        created_at TIMESTAMP,
                        updated_at TIMESTAMP,
                        creator_id BIGINT NOT NULL,
                        opening_hour TIME,
                        closing_hour TIME,
                        image TEXT,
                        address_lat DOUBLE PRECISION,
                        address_lng DOUBLE PRECISION,
                        rating DOUBLE PRECISION DEFAULT 0.0,
                        rating_count INTEGER DEFAULT 0
                    )
                    """);
            statement.execute("""
                    CREATE TABLE menu_item (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        restaurant_id BIGINT NOT NULL,
                        name VARCHAR(255) NOT NULL,
                        description TEXT,
                        price DECIMAL(12,2) NOT NULL,
                        status VARCHAR(20) NOT NULL,
                        image TEXT,
                        created_at TIMESTAMP,
                        updated_at TIMESTAMP
                    )
                    """);
            if (!omitRatings) {
                statement.execute("""
                        CREATE TABLE restaurant_ratings (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            restaurant_id BIGINT NOT NULL,
                            customer_id BIGINT NOT NULL,
                            order_id BIGINT NOT NULL,
                            rating INTEGER NOT NULL,
                            comment TEXT,
                            %s
                            created_at TIMESTAMP
                        )
                        """.formatted(omitRatingStatus ? "" : "status VARCHAR(255) NOT NULL,"));
            }
        }
    }

    private long insertRestaurant(Statement statement, long creatorId) throws Exception {
        statement.executeUpdate("""
                INSERT INTO restaurant (name, creator_id, rating, rating_count, created_at, updated_at)
                VALUES ('Pho House', %d, 0.0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """.formatted(creatorId), Statement.RETURN_GENERATED_KEYS);
        try (ResultSet keys = statement.getGeneratedKeys()) {
            assertThat(keys.next()).isTrue();
            return keys.getLong(1);
        }
    }

    private void insertMenuItem(Statement statement, long restaurantId) throws Exception {
        statement.executeUpdate("""
                INSERT INTO menu_item (restaurant_id, name, price, status, created_at, updated_at)
                VALUES (%d, 'Pho', 50000, 'AVAILABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """.formatted(restaurantId));
    }

    private void insertRating(Statement statement, long restaurantId, long orderId) throws Exception {
        statement.executeUpdate("""
                INSERT INTO restaurant_ratings
                    (restaurant_id, customer_id, order_id, rating, status, created_at)
                VALUES (%d, 20, %d, 5, 'APPROVED', CURRENT_TIMESTAMP)
                """.formatted(restaurantId, orderId));
    }

    private boolean indexExists(Connection connection, String expectedName) throws Exception {
        for (String table : new String[]{"restaurant", "menu_item", "restaurant_ratings"}) {
            try (ResultSet indexes = connection.getMetaData().getIndexInfo(null, null, table, false, false)) {
                while (indexes.next()) {
                    String name = indexes.getString("INDEX_NAME");
                    if (name != null && expectedName.equalsIgnoreCase(name)) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    private long count(Statement statement, String sql) throws Exception {
        try (ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private String databaseUrl(String label) {
        return "jdbc:h2:mem:restaurant_core_migration_" + label + "_" + UUID.randomUUID()
                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";
    }
}
