package db.migration;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/** Owns retained voucher-wallet persistence without enabling voucher checkout. */
public class V1__promotion_schema extends BaseJavaMigration {

    private static final Set<String> VOUCHER_COLUMNS = Set.of(
            "id", "code", "name", "description", "creator_type", "creator_id",
            "reward_type", "discount_value", "max_discount_value", "scope_type",
            "scope_ref_id", "total_quantity", "used_quantity", "usage_limit_per_user",
            "start_time", "end_time", "min_order_value", "voucher_group_id",
            "customer_segment", "active", "created_at", "updated_at");
    private static final Set<String> USER_VOUCHER_COLUMNS = Set.of(
            "id", "user_id", "voucher_id", "status", "order_id", "used_at",
            "created_at", "updated_at");
    private static final Set<String> GROUP_COLUMNS = Set.of(
            "id", "name", "description", "max_per_order");
    private static final Set<String> EXCLUSION_COLUMNS = Set.of("group_id", "excluded_group_id");

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String vouchers = findTable(connection, "vouchers");
        String userVouchers = findTable(connection, "user_vouchers");
        String groups = findTable(connection, "voucher_groups");
        String exclusions = findTable(connection, "voucher_group_exclusions");
        int existing = countPresent(vouchers, userVouchers, groups, exclusions);

        if (existing == 0) {
            createTables(connection);
            vouchers = findTable(connection, "vouchers");
            userVouchers = findTable(connection, "user_vouchers");
            groups = findTable(connection, "voucher_groups");
        } else if (existing != 4) {
            throw new FlywayException("Existing Promotion schema is incomplete: vouchers, user_vouchers, "
                    + "voucher_groups and voucher_group_exclusions must all exist");
        } else {
            requireColumns(connection, vouchers, VOUCHER_COLUMNS, "vouchers");
            requireColumns(connection, userVouchers, USER_VOUCHER_COLUMNS, "user_vouchers");
            requireColumns(connection, groups, GROUP_COLUMNS, "voucher_groups");
            requireColumns(connection, exclusions, EXCLUSION_COLUMNS, "voucher_group_exclusions");
        }

        requireNoDuplicate(connection, "vouchers", "code", "voucher code");
        requireNoDuplicate(connection, "voucher_groups", "name", "voucher-group name");
        requireNoDuplicatePair(connection, "user_vouchers", "user_id", "voucher_id",
                "user/voucher collection");

        if (!hasUniqueIndex(connection, vouchers, Set.of("code"))) {
            execute(connection, "ALTER TABLE vouchers ADD CONSTRAINT uk_vouchers_code UNIQUE (code)");
        }
        if (!hasUniqueIndex(connection, groups, Set.of("name"))) {
            execute(connection, "ALTER TABLE voucher_groups ADD CONSTRAINT uk_voucher_groups_name UNIQUE (name)");
        }
        if (!hasUniqueIndex(connection, userVouchers, Set.of("user_id", "voucher_id"))) {
            execute(connection, """
                    ALTER TABLE user_vouchers
                    ADD CONSTRAINT uk_user_vouchers_user_voucher UNIQUE (user_id, voucher_id)
                    """);
        }

        execute(connection, "CREATE INDEX IF NOT EXISTS idx_vouchers_creator ON vouchers (creator_type, creator_id)");
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_vouchers_active_scope_expiry
                ON vouchers (active, scope_type, scope_ref_id, end_time)
                """);
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_user_vouchers_user_status
                ON user_vouchers (user_id, status)
                """);
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_user_vouchers_order ON user_vouchers (order_id)");
    }

    private void createTables(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE vouchers (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    code VARCHAR(50) NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    description VARCHAR(255),
                    creator_type VARCHAR(255) NOT NULL,
                    creator_id BIGINT,
                    reward_type VARCHAR(255) NOT NULL,
                    discount_value DECIMAL(38,2) NOT NULL,
                    max_discount_value DECIMAL(38,2),
                    scope_type VARCHAR(255) NOT NULL,
                    scope_ref_id BIGINT,
                    total_quantity INTEGER NOT NULL,
                    used_quantity INTEGER NOT NULL,
                    usage_limit_per_user INTEGER NOT NULL,
                    start_time TIMESTAMP NOT NULL,
                    end_time TIMESTAMP NOT NULL,
                    min_order_value DECIMAL(38,2),
                    voucher_group_id BIGINT,
                    customer_segment VARCHAR(255),
                    active BOOLEAN NOT NULL,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    CONSTRAINT uk_vouchers_code UNIQUE (code)
                )
                """);
        execute(connection, """
                CREATE TABLE user_vouchers (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    voucher_id BIGINT NOT NULL,
                    status VARCHAR(255) NOT NULL,
                    order_id BIGINT,
                    used_at TIMESTAMP,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    CONSTRAINT uk_user_vouchers_user_voucher UNIQUE (user_id, voucher_id)
                )
                """);
        execute(connection, """
                CREATE TABLE voucher_groups (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    description VARCHAR(255),
                    max_per_order INTEGER NOT NULL,
                    CONSTRAINT uk_voucher_groups_name UNIQUE (name)
                )
                """);
        execute(connection, """
                CREATE TABLE voucher_group_exclusions (
                    group_id BIGINT NOT NULL,
                    excluded_group_id BIGINT,
                    CONSTRAINT fk_voucher_group_exclusions_group
                        FOREIGN KEY (group_id) REFERENCES voucher_groups (id)
                )
                """);
    }

    private int countPresent(String... tables) {
        int count = 0;
        for (String table : tables) if (table != null) count++;
        return count;
    }

    private void requireNoDuplicate(Connection connection, String table, String column, String label)
            throws SQLException {
        long count = queryCount(connection, "SELECT count(*) FROM (SELECT " + column + " FROM " + table
                + " GROUP BY " + column + " HAVING count(*) > 1) duplicates");
        if (count > 0) {
            throw new FlywayException("Promotion schema contains " + count + " duplicate " + label
                    + " group(s); manual reconciliation is required");
        }
    }

    private void requireNoDuplicatePair(Connection connection, String table, String first, String second,
                                        String label) throws SQLException {
        long count = queryCount(connection, "SELECT count(*) FROM (SELECT " + first + ", " + second
                + " FROM " + table + " GROUP BY " + first + ", " + second
                + " HAVING count(*) > 1) duplicates");
        if (count > 0) {
            throw new FlywayException("Promotion schema contains " + count + " duplicate " + label
                    + " group(s); manual reconciliation is required");
        }
    }

    private void requireColumns(Connection connection, String tableName, Set<String> required,
                                String logicalName) throws SQLException {
        Set<String> columns = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData().getColumns(null, null, tableName, "%")) {
            while (resultSet.next()) columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
        }
        Set<String> missing = new HashSet<>(required);
        missing.removeAll(columns);
        if (!missing.isEmpty()) {
            throw new FlywayException("Existing " + logicalName + " table is missing core column(s): " + missing);
        }
    }

    private boolean hasUniqueIndex(Connection connection, String tableName, Set<String> expectedColumns)
            throws SQLException {
        Map<String, Set<String>> columnsByIndex = new HashMap<>();
        try (ResultSet indexes = connection.getMetaData().getIndexInfo(null, null, tableName, true, false)) {
            while (indexes.next()) {
                String index = indexes.getString("INDEX_NAME");
                String column = indexes.getString("COLUMN_NAME");
                if (index != null && column != null) {
                    columnsByIndex.computeIfAbsent(index.toLowerCase(Locale.ROOT), ignored -> new HashSet<>())
                            .add(column.toLowerCase(Locale.ROOT));
                }
            }
        }
        return columnsByIndex.values().stream().anyMatch(columns -> columns.equals(expectedColumns));
    }

    private long queryCount(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private String findTable(Connection connection, String expectedName) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(null, null, "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String name = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(name)) return name;
            }
        }
        return null;
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
