# Service configuration
spring.application.name=tracking-service
server.port=8090

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000ms
spring.data.redis.database=0

# Logging
logging.level.com.delivery.tracking_service=DEBUG
