package db.migration;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

/** Owns retained Flash Sale campaign/item persistence without enabling checkout. */
public class V1__flash_sale_schema extends BaseJavaMigration {

    private static final Set<String> CAMPAIGN_COLUMNS = Set.of(
            "id", "name", "is_recurring", "start_time", "end_time", "status", "admin_id",
            "created_at", "updated_at");
    private static final Set<String> ITEM_COLUMNS = Set.of(
            "id", "campaign_id", "restaurant_id", "menu_item_id", "original_price",
            "flash_sale_price", "stock_quantity", "sold_quantity", "status", "created_at", "updated_at");

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String campaigns = findTable(connection, "flash_sale_campaigns");
        String items = findTable(connection, "flash_sale_items");
        if (campaigns == null && items == null) {
            createTables(connection);
        } else if (campaigns == null || items == null) {
            throw new FlywayException("Existing Flash Sale schema is incomplete: campaigns and items must both exist");
        } else {
            requireColumns(connection, campaigns, CAMPAIGN_COLUMNS, "flash_sale_campaigns");
            requireColumns(connection, items, ITEM_COLUMNS, "flash_sale_items");
        }
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_flash_campaign_status_start
                ON flash_sale_campaigns (status, start_time)
                """);
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_flash_items_campaign_status
                ON flash_sale_items (campaign_id, status)
                """);
    }

    private void createTables(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE flash_sale_campaigns (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL, is_recurring BOOLEAN NOT NULL,
                    start_time TIME NOT NULL, end_time TIME NOT NULL,
                    status VARCHAR(255) NOT NULL, admin_id BIGINT,
                    created_at TIMESTAMP, updated_at TIMESTAMP
                )
                """);
        execute(connection, """
                CREATE TABLE flash_sale_items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    campaign_id BIGINT NOT NULL, restaurant_id BIGINT NOT NULL,
                    menu_item_id BIGINT NOT NULL, original_price DECIMAL(38,2) NOT NULL,
                    flash_sale_price DECIMAL(38,2) NOT NULL, stock_quantity INTEGER NOT NULL,
                    sold_quantity INTEGER NOT NULL, status VARCHAR(255) NOT NULL,
                    created_at TIMESTAMP, updated_at TIMESTAMP,
                    CONSTRAINT fk_flash_item_campaign FOREIGN KEY (campaign_id)
                        REFERENCES flash_sale_campaigns (id)
                )
                """);
    }

    private void requireColumns(Connection connection, String tableName, Set<String> required,
                                String logicalName) throws SQLException {
        Set<String> columns = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData()
                .getColumns(null, connection.getSchema(), tableName, "%")) {
            while (resultSet.next()) columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
        }
        Set<String> missing = new HashSet<>(required);
        missing.removeAll(columns);
        if (!missing.isEmpty()) {
            throw new FlywayException("Existing " + logicalName + " table is missing core column(s): " + missing);
        }
    }

    private String findTable(Connection connection, String expectedName) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(
                null, connection.getSchema(), "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String name = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(name)) return name;
            }
        }
        return null;
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
