package com.delivery.settlement_service.migration;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.MigrationVersion;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class SettlementCoreFlywayMigrationTest {

    @Test
    void cleanSchemaCreatesBalanceLedgerPaymentTablesAndIndexes() throws Exception {
        String url = databaseUrl("clean");
        migrate(url);

        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            insertBalance(statement);
            insertTransaction(statement);
            insertPayment(statement);
            assertThat(count(statement, "SELECT count(*) FROM balances")).isEqualTo(1);
            assertThat(count(statement, "SELECT count(*) FROM transactions")).isEqualTo(1);
            assertThat(count(statement, "SELECT count(*) FROM payment_orders")).isEqualTo(1);
            assertThat(indexExists(connection, "idx_transactions_entity_status")).isTrue();
            assertThat(indexExists(connection, "idx_payment_entity")).isTrue();
        }
    }

    @Test
    void legacySchemaPreservesFinancialRows() throws Exception {
        String url = databaseUrl("legacy");
        createLegacySchema(url, false, false);
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            insertBalance(statement);
            insertTransaction(statement);
            insertPayment(statement);
        }

        migrate(url);

        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            assertThat(count(statement, "SELECT count(*) FROM balances")).isEqualTo(1);
            assertThat(count(statement, "SELECT count(*) FROM transactions")).isEqualTo(1);
            assertThat(count(statement, "SELECT count(*) FROM payment_orders")).isEqualTo(1);
        }
    }

    @Test
    void missingCoreColumnStopsMigrationInsteadOfGuessingMoneyState() throws Exception {
        String url = databaseUrl("missing_core");
        createLegacySchema(url, true, false);

        assertThatThrownBy(() -> migrate(url))
                .isInstanceOf(FlywayException.class)
                .rootCause()
                .hasMessageContaining("missing core column")
                .hasMessageContaining("currency");
    }

    @Test
    void incompleteLegacyTableSetStopsMigration() throws Exception {
        String url = databaseUrl("incomplete");
        createLegacySchema(url, false, true);

        assertThatThrownBy(() -> migrate(url))
                .isInstanceOf(FlywayException.class)
                .rootCause()
                .hasMessageContaining("schema is incomplete");
    }

    private void migrate(String url) {
        Flyway.configure()
                .dataSource(url, "sa", "")
                .baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("0"))
                .load()
                .migrate();
    }

    private void createLegacySchema(String url, boolean omitPaymentCurrency, boolean omitPayments)
            throws Exception {
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE balances (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        entity_id BIGINT NOT NULL,
                        entity_type VARCHAR(20) NOT NULL,
                        available_balance DECIMAL(12,2) NOT NULL,
                        pending_balance DECIMAL(12,2) NOT NULL,
                        holding_balance DECIMAL(12,2) NOT NULL,
                        deposit_balance DECIMAL(12,2) NOT NULL,
                        total_deposited DECIMAL(12,2) NOT NULL,
                        total_cod_collected DECIMAL(12,2) NOT NULL,
                        created_at TIMESTAMP,
                        updated_at TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE transactions (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        entity_id BIGINT NOT NULL,
                        entity_type VARCHAR(20) NOT NULL,
                        order_id BIGINT,
                        direction VARCHAR(10) NOT NULL,
                        reason VARCHAR(30) NOT NULL,
                        amount DECIMAL(12,2) NOT NULL,
                        description TEXT,
                        status VARCHAR(20) NOT NULL,
                        wallet_type VARCHAR(20) NOT NULL,
                        processed_at TIMESTAMP,
                        processed_by BIGINT,
                        created_at TIMESTAMP NOT NULL
                    )
                    """);
            if (!omitPayments) {
                statement.execute("""
                        CREATE TABLE payment_orders (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            payment_ref VARCHAR(64) NOT NULL,
                            entity_id BIGINT NOT NULL,
                            entity_type VARCHAR(20) NOT NULL,
                            order_id BIGINT,
                            provider VARCHAR(30) NOT NULL,
                            amount DECIMAL(12,2) NOT NULL,
                            %s
                            purpose VARCHAR(30) NOT NULL,
                            status VARCHAR(20) NOT NULL,
                            provider_transaction_id VARCHAR(128),
                            payment_url TEXT,
                            callback_payload TEXT,
                            settlement_transaction_id BIGINT,
                            return_url TEXT,
                            ip_address VARCHAR(45),
                            created_at TIMESTAMP NOT NULL,
                            updated_at TIMESTAMP,
                            expired_at TIMESTAMP
                        )
                        """.formatted(omitPaymentCurrency ? "" : "currency VARCHAR(10) NOT NULL,"));
            }
        }
    }

    private void insertBalance(Statement statement) throws Exception {
        statement.executeUpdate("""
                INSERT INTO balances
                    (entity_id, entity_type, available_balance, pending_balance, holding_balance,
                     deposit_balance, total_deposited, total_cod_collected, created_at, updated_at)
                VALUES (7, 'SHIPPER', 0, 0, 0, 100000, 100000, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """);
    }

    private void insertTransaction(Statement statement) throws Exception {
        statement.executeUpdate("""
                INSERT INTO transactions
                    (entity_id, entity_type, order_id, direction, reason, amount, status,
                     wallet_type, created_at)
                VALUES (7, 'SHIPPER', 10, 'CREDIT', 'DELIVERY_FEE', 15000, 'COMPLETED',
                        'EARNINGS', CURRENT_TIMESTAMP)
                """);
    }

    private void insertPayment(Statement statement) throws Exception {
        statement.executeUpdate("""
                INSERT INTO payment_orders
                    (payment_ref, entity_id, entity_type, provider, amount, currency, purpose,
                     status, created_at, updated_at)
                VALUES ('payment-1', 7, 'SHIPPER', 'DISABLED_TEST', 100000, 'VND',
                        'DEPOSIT_TOPUP', 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """);
    }

    private boolean indexExists(Connection connection, String expectedName) throws Exception {
        for (String table : new String[]{"transactions", "payment_orders"}) {
            try (ResultSet indexes = connection.getMetaData().getIndexInfo(null, null, table, false, false)) {
                while (indexes.next()) {
                    String name = indexes.getString("INDEX_NAME");
                    if (name != null && expectedName.equalsIgnoreCase(name)) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    private long count(Statement statement, String sql) throws Exception {
        try (ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private String databaseUrl(String label) {
        return "jdbc:h2:mem:settlement_core_migration_" + label + "_" + UUID.randomUUID()
                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";
    }
}
