package db.migration;

import java.sql.Connection;
import java.sql.Statement;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

/** Additive shipper-domain identity projection outbox. */
public class V6__shipper_identity_outbox extends BaseJavaMigration {
    @Override public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        execute(connection, "CREATE TABLE IF NOT EXISTS shipper_identity_outbox_events ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,event_id UUID NOT NULL UNIQUE,"
                + "event_type VARCHAR(128) NOT NULL,aggregate_id BIGINT NOT NULL,topic VARCHAR(255) NOT NULL,"
                + "event_key VARCHAR(128) NOT NULL,payload TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,"
                + "available_at TIMESTAMP NOT NULL,published_at TIMESTAMP,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL)");
        execute(connection, "CREATE UNIQUE INDEX IF NOT EXISTS uk_shipper_identity_outbox_type_aggregate "
                + "ON shipper_identity_outbox_events (event_type, aggregate_id)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_shipper_identity_outbox_pending "
                + "ON shipper_identity_outbox_events (published_at, available_at, id)");
    }
    private void execute(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement()) { statement.execute(sql); }
    }
}
