package com.delivery.delivery_service.migration;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.test.context.ContextConfiguration;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

@SpringBootTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:delivery_flyway_validation;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.flyway.enabled=true",
        "spring.flyway.baseline-on-migrate=true",
        "spring.flyway.baseline-version=9",
        "spring.jpa.hibernate.ddl-auto=validate",
        "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect",
        "spring.sql.init.mode=never",
        "spring.kafka.listener.auto-startup=false",
        "app.outbox.relay-enabled=false"
})
@ContextConfiguration(initializers = DeliveryMigrationSchemaValidationTest.SchemaInitializer.class)
class DeliveryMigrationSchemaValidationTest {

    private static final String URL = "jdbc:h2:mem:delivery_flyway_validation;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";

    static class SchemaInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {
        @Override
        public void initialize(ConfigurableApplicationContext applicationContext) {
            try (Connection connection = DriverManager.getConnection(URL, "sa", "");
                 Statement statement = connection.createStatement()) {
                statement.execute("""
                        CREATE TABLE deliveries (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            create_event_id UUID NOT NULL UNIQUE,
                            order_id BIGINT NOT NULL UNIQUE,
                            shipper_id BIGINT, offered_shipper_id BIGINT, offer_expires_at TIMESTAMP,
                            status VARCHAR(255), pickup_address TEXT, pickup_lat DOUBLE PRECISION,
                            pickup_lng DOUBLE PRECISION, delivery_address TEXT,
                            delivery_lat DOUBLE PRECISION, delivery_lng DOUBLE PRECISION,
                            shipper_current_lat DOUBLE PRECISION, shipper_current_lng DOUBLE PRECISION,
                            assigned_at TIMESTAMP, picked_up_at TIMESTAMP, delivered_at TIMESTAMP,
                            estimated_delivery_time TIMESTAMP, shipping_fee DECIMAL(12,2),
                            total_price DECIMAL(12,2), payment_method VARCHAR(255), notes TEXT,
                            reject_reason TEXT, created_at TIMESTAMP, updated_at TIMESTAMP,
                            creator_id BIGINT NOT NULL, restaurant_id BIGINT, restaurant_owner_id BIGINT,
                            CONSTRAINT deliveries_status_check CHECK (status IN ('PENDING'))
                        )
                        """);
                statement.execute("""
                        CREATE TABLE outbox_events (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            event_id UUID NOT NULL UNIQUE, aggregate_type VARCHAR(64) NOT NULL,
                            aggregate_id VARCHAR(255) NOT NULL, event_type VARCHAR(128) NOT NULL,
                            topic VARCHAR(255) NOT NULL, event_key VARCHAR(255) NOT NULL,
                            payload TEXT NOT NULL, status VARCHAR(16) NOT NULL,
                            attempts INTEGER NOT NULL, next_attempt_at TIMESTAMP NOT NULL,
                            created_at TIMESTAMP NOT NULL, sent_at TIMESTAMP,
                            last_error VARCHAR(2000)
                        )
                        """);
            } catch (Exception exception) {
                throw new IllegalStateException("Cannot prepare Delivery V9 schema", exception);
            }
        }
    }

    @Test
    void versionTenSchemaMatchesDeliveryJpaEntitiesWithoutHibernateMutation() {
    }
}
