package com.delivery.delivery_service.migration;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationVersion;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class DeliveryV10FlywayMigrationTest {

    @Test
    void versionTenRemovesStartupPatchConstraintAndAddsRepositoryIndexes() throws Exception {
        String url = databaseUrl();
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE deliveries (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        shipper_id BIGINT, status VARCHAR(32), created_at TIMESTAMP,
                        shipping_fee DECIMAL(12,2), total_price DECIMAL(12,2),
                        gross_shipping_fee DECIMAL(12,2), customer_shipping_fee DECIMAL(12,2),
                        subtotal_price DECIMAL(12,2), item_discount DECIMAL(12,2),
                        shop_discount DECIMAL(12,2), shipping_discount DECIMAL(12,2),
                        platform_subsidy DECIMAL(12,2),
                        CONSTRAINT deliveries_status_check CHECK (status IN ('PENDING'))
                    )
                    """);
            statement.execute("""
                    CREATE TABLE outbox_events (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        event_id UUID NOT NULL UNIQUE,
                        aggregate_type VARCHAR(64) NOT NULL,
                        aggregate_id VARCHAR(255) NOT NULL,
                        event_type VARCHAR(128) NOT NULL,
                        topic VARCHAR(255) NOT NULL,
                        event_key VARCHAR(255) NOT NULL,
                        payload TEXT NOT NULL,
                        status VARCHAR(16) NOT NULL,
                        attempts INTEGER NOT NULL,
                        next_attempt_at TIMESTAMP NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        sent_at TIMESTAMP,
                        last_error VARCHAR(2000)
                    )
                    """);
        }

        Flyway.configure().dataSource(url, "sa", "")
                .baselineOnMigrate(true).baselineVersion(MigrationVersion.fromVersion("9"))
                .load().migrate();

        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                    INSERT INTO deliveries (shipper_id, status, created_at)
                    VALUES (7, 'WAIT_SHIPPER_CONFIRM', CURRENT_TIMESTAMP)
                    """);
            assertThat(indexExists(connection, "idx_deliveries_shipper_created")).isTrue();
            assertThat(indexExists(connection, "idx_deliveries_status_created")).isTrue();
        }
    }

    private boolean indexExists(Connection connection, String expected) throws Exception {
        try (ResultSet indexes = connection.getMetaData().getIndexInfo(
                null, connection.getSchema(), "deliveries", false, false)) {
            while (indexes.next()) {
                String name = indexes.getString("INDEX_NAME");
                if (name != null && expected.equalsIgnoreCase(name)) return true;
            }
        }
        return false;
    }

    private String databaseUrl() {
        return "jdbc:h2:mem:delivery_v10_" + UUID.randomUUID()
                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";
    }
}
