server:
  port: 8088

spring:
  application:
    name: search-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: search-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    listener:
      auto-startup: ${SEARCH_KAFKA_LISTENER_AUTO_STARTUP:true}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
  data:
    elasticsearch:
      repositories:
        enabled: ${APP_ELASTICSEARCH_ENABLED:false}

app:
  search:
  elasticsearch:
    enabled: ${APP_ELASTICSEARCH_ENABLED:false}
