CREATE TABLE IF NOT EXISTS saga_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    event_key VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('PENDING', 'SENT', 'DEAD')),
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP NULL,
    last_error VARCHAR(2000) NULL,
    CONSTRAINT uk_saga_outbox_event_id UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS idx_saga_outbox_pending
    ON saga_outbox_events (status, next_attempt_at, created_at);
CREATE INDEX IF NOT EXISTS idx_saga_outbox_aggregate
    ON saga_outbox_events (aggregate_id, created_at);
