package db.migration;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

/** Owns the complete Notification JPA schema and its durable event-dedup boundary. */
public class V1__notification_schema extends BaseJavaMigration {

    private static final String TABLE = "notifications";
    private static final String DEDUP_CONSTRAINT = "uk_notifications_deduplication_key";
    private static final Set<String> REQUIRED_CORE_COLUMNS = Set.of(
            "id", "user_id", "title", "message", "type", "priority", "status", "is_read",
            "related_entity_id", "related_entity_type", "data", "sent_at", "read_at",
            "created_at", "updated_at");

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String tableName = findTable(connection, TABLE);
        if (tableName == null) {
            createTable(connection);
            tableName = findTable(connection, TABLE);
        } else {
            requireCoreSchema(connection, tableName);
            addCompatibilityColumns(connection);
        }

        requireNoDuplicateDeduplicationKeys(connection);
        if (!hasIndex(connection, tableName, DEDUP_CONSTRAINT)) {
            execute(connection, """
                    ALTER TABLE notifications
                    ADD CONSTRAINT uk_notifications_deduplication_key UNIQUE (deduplication_key)
                    """);
        }
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_notifications_user_created
                ON notifications (user_id, created_at)
                """);
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_notifications_user_read_created
                ON notifications (user_id, is_read, created_at)
                """);
    }

    private void createTable(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE notifications (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    message TEXT NOT NULL,
                    type VARCHAR(255) NOT NULL,
                    priority VARCHAR(255),
                    status VARCHAR(255),
                    is_read BOOLEAN,
                    related_entity_id BIGINT,
                    related_entity_type VARCHAR(255),
                    data TEXT,
                    sent_at TIMESTAMP,
                    read_at TIMESTAMP,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    creator_id BIGINT,
                    deduplication_key VARCHAR(200)
                )
                """);
    }

    private void addCompatibilityColumns(Connection connection) throws SQLException {
        execute(connection, "ALTER TABLE notifications ADD COLUMN IF NOT EXISTS creator_id BIGINT");
        execute(connection, """
                ALTER TABLE notifications
                ADD COLUMN IF NOT EXISTS deduplication_key VARCHAR(200)
                """);
    }

    private void requireCoreSchema(Connection connection, String tableName) throws SQLException {
        Set<String> columns = new HashSet<>();
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet resultSet = metadata.getColumns(null, null, tableName, "%")) {
            while (resultSet.next()) {
                columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
            }
        }
        Set<String> missing = new HashSet<>(REQUIRED_CORE_COLUMNS);
        missing.removeAll(columns);
        if (!missing.isEmpty()) {
            throw new FlywayException("Existing notifications table is missing core column(s): " + missing);
        }
    }

    private void requireNoDuplicateDeduplicationKeys(Connection connection) throws SQLException {
        long duplicates = queryCount(connection, """
                SELECT count(*)
                FROM (
                    SELECT deduplication_key
                    FROM notifications
                    WHERE deduplication_key IS NOT NULL
                    GROUP BY deduplication_key
                    HAVING count(*) > 1
                ) duplicate_keys
                """);
        if (duplicates > 0) {
            throw new FlywayException("Notification schema contains " + duplicates
                    + " duplicate deduplication key group(s); manual reconciliation is required");
        }
    }

    private long queryCount(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private String findTable(Connection connection, String expectedName) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(null, null, "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(tableName)) {
                    return tableName;
                }
            }
        }
        return null;
    }

    private boolean hasIndex(Connection connection, String tableName, String expectedName)
            throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet indexes = metadata.getIndexInfo(null, null, tableName, true, false)) {
            while (indexes.next()) {
                String indexName = indexes.getString("INDEX_NAME");
                if (indexName != null && expectedName.equalsIgnoreCase(indexName)) {
                    return true;
                }
            }
        }
        return false;
    }
}
