package com.delivery.promotion_service.migration;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.MigrationVersion;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class PromotionFlywayMigrationTest {

    @Test
    void cleanSchemaCreatesVoucherWalletAndQueryIndexes() throws Exception {
        String url = databaseUrl("clean");
        migrate(url);
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            insertVoucher(statement, "WELCOME");
            statement.executeUpdate("""
                    INSERT INTO user_vouchers
                        (user_id, voucher_id, status, created_at, updated_at)
                    VALUES (7, 1, 'SAVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                    """);
            assertThat(count(statement, "SELECT count(*) FROM vouchers")).isEqualTo(1);
            assertThat(indexExists(connection, "idx_vouchers_creator")).isTrue();
            assertThat(indexExists(connection, "idx_user_vouchers_user_status")).isTrue();
        }
    }

    @Test
    void legacySchemaPreservesRowsAndAddsIndexes() throws Exception {
        String url = databaseUrl("legacy");
        createLegacySchema(url, false, false);
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            insertVoucher(statement, "KEEP");
        }

        migrate(url);

        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            assertThat(count(statement, "SELECT count(*) FROM vouchers")).isEqualTo(1);
            assertThat(indexExists(connection, "idx_vouchers_active_scope_expiry")).isTrue();
        }
    }

    @Test
    void missingCoreColumnStopsMigration() throws Exception {
        String url = databaseUrl("missing");
        createLegacySchema(url, true, false);

        assertThatThrownBy(() -> migrate(url)).isInstanceOf(FlywayException.class).rootCause()
                .hasMessageContaining("missing core column").hasMessageContaining("used_quantity");
    }

    @Test
    void incompleteSchemaStopsMigration() throws Exception {
        String url = databaseUrl("incomplete");
        createLegacySchema(url, false, true);

        assertThatThrownBy(() -> migrate(url)).isInstanceOf(FlywayException.class).rootCause()
                .hasMessageContaining("schema is incomplete");
    }

    @Test
    void duplicateVoucherIdentityStopsMigration() throws Exception {
        String url = databaseUrl("duplicate");
        createLegacySchema(url, false, false);
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            insertVoucher(statement, "DUP");
            insertVoucher(statement, "DUP");
        }

        assertThatThrownBy(() -> migrate(url)).isInstanceOf(FlywayException.class).rootCause()
                .hasMessageContaining("duplicate voucher code");
    }

    private void migrate(String url) {
        Flyway.configure().dataSource(url, "sa", "")
                .baselineOnMigrate(true).baselineVersion(MigrationVersion.fromVersion("0"))
                .load().migrate();
    }

    private void createLegacySchema(String url, boolean omitUsedQuantity, boolean omitExclusions)
            throws Exception {
        try (Connection connection = DriverManager.getConnection(url, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE vouchers (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL,
                        description VARCHAR(255), creator_type VARCHAR(255) NOT NULL,
                        creator_id BIGINT, reward_type VARCHAR(255) NOT NULL,
                        discount_value DECIMAL(38,2) NOT NULL, max_discount_value DECIMAL(38,2),
                        scope_type VARCHAR(255) NOT NULL, scope_ref_id BIGINT,
                        total_quantity INTEGER NOT NULL,
                        %s
                        usage_limit_per_user INTEGER NOT NULL, start_time TIMESTAMP NOT NULL,
                        end_time TIMESTAMP NOT NULL, min_order_value DECIMAL(38,2),
                        voucher_group_id BIGINT, customer_segment VARCHAR(255), active BOOLEAN NOT NULL,
                        created_at TIMESTAMP, updated_at TIMESTAMP
                    )
                    """.formatted(omitUsedQuantity ? "" : "used_quantity INTEGER NOT NULL,"));
            statement.execute("""
                    CREATE TABLE user_vouchers (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL, voucher_id BIGINT NOT NULL, status VARCHAR(255) NOT NULL,
                        order_id BIGINT, used_at TIMESTAMP, created_at TIMESTAMP, updated_at TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE voucher_groups (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL, description VARCHAR(255), max_per_order INTEGER NOT NULL
                    )
                    """);
            if (!omitExclusions) {
                statement.execute("""
                        CREATE TABLE voucher_group_exclusions (
                            group_id BIGINT NOT NULL, excluded_group_id BIGINT
                        )
                        """);
            }
        }
    }

    private void insertVoucher(Statement statement, String code) throws Exception {
        statement.executeUpdate("""
                INSERT INTO vouchers
                    (code, name, creator_type, reward_type, discount_value, scope_type,
                     total_quantity, used_quantity, usage_limit_per_user, start_time, end_time, active)
                VALUES ('%s', 'Voucher', 'PLATFORM', 'FIXED', 10000, 'ALL',
                        10, 0, 1, CURRENT_TIMESTAMP, DATEADD('DAY', 1, CURRENT_TIMESTAMP), true)
                """.formatted(code));
    }

    private boolean indexExists(Connection connection, String expectedName) throws Exception {
        for (String table : new String[]{"vouchers", "user_vouchers"}) {
            try (ResultSet indexes = connection.getMetaData().getIndexInfo(null, null, table, false, false)) {
                while (indexes.next()) {
                    String name = indexes.getString("INDEX_NAME");
                    if (name != null && expectedName.equalsIgnoreCase(name)) return true;
                }
            }
        }
        return false;
    }

    private long count(Statement statement, String sql) throws Exception {
        try (ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private String databaseUrl(String label) {
        return "jdbc:h2:mem:promotion_migration_" + label + "_" + UUID.randomUUID()
                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";
    }
}
