CREATE TABLE IF NOT EXISTS daily_item_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_date DATE NOT NULL,
    restaurant_id BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    menu_item_name VARCHAR(255) NOT NULL,
    ordered_quantity BIGINT NOT NULL DEFAULT 0,
    cancelled_quantity BIGINT NOT NULL DEFAULT 0,
    ordered_revenue DECIMAL(15,2) NOT NULL DEFAULT 0,
    cancelled_revenue DECIMAL(15,2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_daily_item_sales_scope
        UNIQUE (stat_date, restaurant_id, menu_item_id)
);

CREATE INDEX IF NOT EXISTS idx_daily_item_sales_date
    ON daily_item_sales (stat_date);

CREATE INDEX IF NOT EXISTS idx_daily_item_sales_restaurant_date
    ON daily_item_sales (restaurant_id, stat_date);
