package db.migration;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

/** Owns restaurant catalog and rating tables previously managed by Hibernate update. */
public class V2__restaurant_core_schema extends BaseJavaMigration {

    private static final Set<String> RESTAURANT_COLUMNS = Set.of(
            "id", "name", "address", "description", "phone", "created_at", "updated_at",
            "creator_id", "opening_hour", "closing_hour", "image", "address_lat", "address_lng",
            "rating", "rating_count");
    private static final Set<String> MENU_COLUMNS = Set.of(
            "id", "restaurant_id", "name", "description", "price", "status", "image",
            "created_at", "updated_at");
    private static final Set<String> RATING_COLUMNS = Set.of(
            "id", "restaurant_id", "customer_id", "order_id", "rating", "comment", "status",
            "created_at");

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String restaurants = findTable(connection, "restaurant");
        String menu = findTable(connection, "menu_item");
        String ratings = findTable(connection, "restaurant_ratings");
        int existingTables = (restaurants == null ? 0 : 1) + (menu == null ? 0 : 1) + (ratings == null ? 0 : 1);

        if (existingTables == 0) {
            createCoreTables(connection);
        } else if (existingTables != 3) {
            throw new FlywayException("Existing Restaurant schema is incomplete: restaurant, menu_item, "
                    + "and restaurant_ratings must all exist");
        } else {
            requireColumns(connection, restaurants, RESTAURANT_COLUMNS, "restaurant");
            requireColumns(connection, menu, MENU_COLUMNS, "menu_item");
            requireColumns(connection, ratings, RATING_COLUMNS, "restaurant_ratings");
        }

        createQueryIndexes(connection);
    }

    private void createCoreTables(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE restaurant (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    address TEXT,
                    description TEXT,
                    phone VARCHAR(20),
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    creator_id BIGINT NOT NULL,
                    opening_hour TIME,
                    closing_hour TIME,
                    image TEXT,
                    address_lat DOUBLE PRECISION,
                    address_lng DOUBLE PRECISION,
                    rating DOUBLE PRECISION DEFAULT 0.0,
                    rating_count INTEGER DEFAULT 0
                )
                """);
        execute(connection, """
                CREATE TABLE menu_item (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    restaurant_id BIGINT NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    description TEXT,
                    price DECIMAL(12,2) NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    image TEXT,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    CONSTRAINT fk_menu_item_restaurant
                        FOREIGN KEY (restaurant_id) REFERENCES restaurant (id)
                )
                """);
        execute(connection, """
                CREATE TABLE restaurant_ratings (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    restaurant_id BIGINT NOT NULL,
                    customer_id BIGINT NOT NULL,
                    order_id BIGINT NOT NULL,
                    rating INTEGER NOT NULL,
                    comment TEXT,
                    status VARCHAR(255) NOT NULL,
                    created_at TIMESTAMP,
                    CONSTRAINT uk_restaurant_ratings_order UNIQUE (order_id)
                )
                """);
    }

    private void createQueryIndexes(Connection connection) throws SQLException {
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_restaurant_creator ON restaurant (creator_id)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_restaurant_phone ON restaurant (phone)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_menu_restaurant_status ON menu_item (restaurant_id, status)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_menu_status ON menu_item (status)");
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_restaurant_ratings_restaurant_status
                ON restaurant_ratings (restaurant_id, status)
                """);
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_restaurant_ratings_customer ON restaurant_ratings (customer_id)");
    }

    private void requireColumns(Connection connection, String tableName, Set<String> required,
                                String logicalName) throws SQLException {
        Set<String> columns = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData().getColumns(null, null, tableName, "%")) {
            while (resultSet.next()) {
                columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
            }
        }
        Set<String> missing = new HashSet<>(required);
        missing.removeAll(columns);
        if (!missing.isEmpty()) {
            throw new FlywayException("Existing " + logicalName + " table is missing core column(s): " + missing);
        }
    }

    private String findTable(Connection connection, String expectedName) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(null, null, "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(tableName)) {
                    return tableName;
                }
            }
        }
        return null;
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
