ALTER TABLE deliveries
    ADD COLUMN IF NOT EXISTS offered_matching_session_id VARCHAR(36);

CREATE TABLE IF NOT EXISTS delivery_offer_session_tombstones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id BIGINT NOT NULL,
    matching_session_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_delivery_offer_session UNIQUE (delivery_id, matching_session_id)
);

CREATE INDEX IF NOT EXISTS idx_delivery_offer_session_tombstones_delivery
    ON delivery_offer_session_tombstones (delivery_id, created_at);
