package db.migration;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

/** Owns the persistence schema for the disabled Livestream capability. */
public class V1__livestream_schema extends BaseJavaMigration {

    private static final Set<String> LIVESTREAM_COLUMNS = Set.of(
            "id", "seller_id", "restaurant_id", "title", "description", "status",
            "stream_provider", "room_id", "channel_name", "started_at", "ended_at",
            "view_count", "created_at", "updated_at");
    private static final Set<String> PRODUCT_COLUMNS = Set.of(
            "id", "livestream_id", "product_id", "product_name", "product_image",
            "restaurant_id", "restaurant_name", "price_at_live", "is_pinned",
            "created_at", "pinned_at");
    private static final Set<String> EVENT_COLUMNS = Set.of(
            "id", "livestream_id", "type", "payload", "created_at");

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String livestreams = findTable(connection, "livestreams");
        String products = findTable(connection, "livestream_products");
        String events = findTable(connection, "livestream_events");
        int existing = (livestreams == null ? 0 : 1) + (products == null ? 0 : 1)
                + (events == null ? 0 : 1);
        if (existing == 0) {
            createTables(connection);
        } else if (existing != 3) {
            throw new FlywayException("Existing Livestream schema is incomplete: livestream, product and event tables must exist");
        } else {
            requireColumns(connection, livestreams, LIVESTREAM_COLUMNS, "livestreams");
            requireColumns(connection, products, PRODUCT_COLUMNS, "livestream_products");
            requireColumns(connection, events, EVENT_COLUMNS, "livestream_events");
        }

        requireNoDuplicates(connection, "livestreams", "room_id", "duplicate room_id");
        requireNoDuplicates(connection, "livestreams", "channel_name", "duplicate channel_name");
        requireNoDuplicates(connection, "livestream_products", "livestream_id, product_id",
                "duplicate livestream product scope");
        addConstraintIfMissing(connection, "livestreams", "uk_livestream_room", "UNIQUE (room_id)");
        addConstraintIfMissing(connection, "livestreams", "uk_livestream_channel", "UNIQUE (channel_name)");
        addConstraintIfMissing(connection, "livestream_products", "uk_livestream_product_scope",
                "UNIQUE (livestream_id, product_id)");
        createIndexes(connection);
    }

    private void createTables(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE livestreams (
                    id UUID PRIMARY KEY, seller_id BIGINT NOT NULL, restaurant_id BIGINT NOT NULL,
                    title VARCHAR(255) NOT NULL, description TEXT, status VARCHAR(255) NOT NULL,
                    stream_provider VARCHAR(255) NOT NULL, room_id VARCHAR(255) NOT NULL,
                    channel_name VARCHAR(255) NOT NULL, started_at TIMESTAMP, ended_at TIMESTAMP,
                    view_count BIGINT NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
                )
                """);
        execute(connection, """
                CREATE TABLE livestream_products (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, livestream_id UUID NOT NULL,
                    product_id BIGINT NOT NULL, product_name VARCHAR(255), product_image TEXT,
                    restaurant_id BIGINT, restaurant_name VARCHAR(255), price_at_live DECIMAL(12,2),
                    is_pinned BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL, pinned_at TIMESTAMP
                )
                """);
        execute(connection, """
                CREATE TABLE livestream_events (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, livestream_id UUID NOT NULL,
                    type VARCHAR(255) NOT NULL, payload TEXT, created_at TIMESTAMP NOT NULL
                )
                """);
    }

    private void createIndexes(Connection connection) throws SQLException {
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_livestream_status_created ON livestreams (status, created_at DESC)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_livestream_seller_created ON livestreams (seller_id, created_at DESC)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_livestream_restaurant_created ON livestreams (restaurant_id, created_at DESC)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_livestream_product_pinned ON livestream_products (livestream_id, is_pinned)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_livestream_event_stream ON livestream_events (livestream_id)");
    }

    private void requireNoDuplicates(Connection connection, String table, String columns, String label)
            throws SQLException {
        long groups = queryCount(connection, "SELECT count(*) FROM (SELECT " + columns + " FROM " + table
                + " GROUP BY " + columns + " HAVING count(*) > 1) duplicates");
        if (groups > 0) {
            throw new FlywayException("Livestream schema contains " + groups + " " + label
                    + " group(s); manual reconciliation is required");
        }
    }

    private void addConstraintIfMissing(Connection connection, String table, String constraint,
                                        String definition) throws SQLException {
        if (!hasIndexNamedLike(connection, table, constraint)) {
            execute(connection, "ALTER TABLE " + table + " ADD CONSTRAINT " + constraint + " " + definition);
        }
    }

    private boolean hasIndexNamedLike(Connection connection, String table, String expected) throws SQLException {
        try (ResultSet indexes = connection.getMetaData().getIndexInfo(
                null, connection.getSchema(), table, true, false)) {
            while (indexes.next()) {
                String name = indexes.getString("INDEX_NAME");
                if (name != null && name.toLowerCase(Locale.ROOT).startsWith(expected.toLowerCase(Locale.ROOT))) {
                    return true;
                }
            }
        }
        return false;
    }

    private void requireColumns(Connection connection, String table, Set<String> required, String logicalName)
            throws SQLException {
        Set<String> columns = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData()
                .getColumns(null, connection.getSchema(), table, "%")) {
            while (resultSet.next()) columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
        }
        Set<String> missing = new HashSet<>(required);
        missing.removeAll(columns);
        if (!missing.isEmpty()) {
            throw new FlywayException("Existing " + logicalName + " table is missing core column(s): " + missing);
        }
    }

    private long queryCount(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement(); ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private String findTable(Connection connection, String expected) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(null, connection.getSchema(), "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String name = tables.getString("TABLE_NAME");
                if (expected.equalsIgnoreCase(name)) return name;
            }
        }
        return null;
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
