package db.migration;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

/** Owns the complete Settlement balance, ledger and disabled-payment persistence schema. */
public class V2__settlement_core_schema extends BaseJavaMigration {

    private static final Set<String> BALANCE_COLUMNS = Set.of(
            "id", "entity_id", "entity_type", "available_balance", "pending_balance",
            "holding_balance", "deposit_balance", "total_deposited", "total_cod_collected",
            "created_at", "updated_at");
    private static final Set<String> TRANSACTION_COLUMNS = Set.of(
            "id", "entity_id", "entity_type", "order_id", "direction", "reason", "amount",
            "description", "status", "wallet_type", "processed_at", "processed_by", "created_at");
    private static final Set<String> PAYMENT_COLUMNS = Set.of(
            "id", "payment_ref", "entity_id", "entity_type", "order_id", "provider", "amount",
            "currency", "purpose", "status", "provider_transaction_id", "payment_url",
            "callback_payload", "settlement_transaction_id", "return_url", "ip_address",
            "created_at", "updated_at", "expired_at");

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String balances = findTable(connection, "balances");
        String transactions = findTable(connection, "transactions");
        String payments = findTable(connection, "payment_orders");
        int existingTables = (balances == null ? 0 : 1)
                + (transactions == null ? 0 : 1)
                + (payments == null ? 0 : 1);

        if (existingTables == 0) {
            createCoreTables(connection);
        } else if (existingTables != 3) {
            throw new FlywayException("Existing Settlement schema is incomplete: balances, transactions, "
                    + "and payment_orders must all exist");
        } else {
            requireColumns(connection, balances, BALANCE_COLUMNS, "balances");
            requireColumns(connection, transactions, TRANSACTION_COLUMNS, "transactions");
            requireColumns(connection, payments, PAYMENT_COLUMNS, "payment_orders");
        }

        createQueryIndexes(connection);
    }

    private void createCoreTables(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE balances (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    entity_id BIGINT NOT NULL,
                    entity_type VARCHAR(20) NOT NULL,
                    available_balance DECIMAL(12,2) NOT NULL,
                    pending_balance DECIMAL(12,2) NOT NULL,
                    holding_balance DECIMAL(12,2) NOT NULL,
                    deposit_balance DECIMAL(12,2) DEFAULT 0.00 NOT NULL,
                    total_deposited DECIMAL(12,2) DEFAULT 0.00 NOT NULL,
                    total_cod_collected DECIMAL(12,2) DEFAULT 0.00 NOT NULL,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    CONSTRAINT uk_balances_entity UNIQUE (entity_id, entity_type)
                )
                """);
        execute(connection, """
                CREATE TABLE transactions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    entity_id BIGINT NOT NULL,
                    entity_type VARCHAR(20) NOT NULL,
                    order_id BIGINT,
                    direction VARCHAR(10) NOT NULL,
                    reason VARCHAR(30) NOT NULL,
                    amount DECIMAL(12,2) NOT NULL,
                    description TEXT,
                    status VARCHAR(20) NOT NULL,
                    wallet_type VARCHAR(20) DEFAULT 'EARNINGS' NOT NULL,
                    processed_at TIMESTAMP,
                    processed_by BIGINT,
                    created_at TIMESTAMP NOT NULL,
                    CONSTRAINT uk_transactions_order_ledger_entry UNIQUE
                        (order_id, entity_id, entity_type, reason, wallet_type, direction)
                )
                """);
        execute(connection, """
                CREATE TABLE payment_orders (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    payment_ref VARCHAR(64) NOT NULL,
                    entity_id BIGINT NOT NULL,
                    entity_type VARCHAR(20) NOT NULL,
                    order_id BIGINT,
                    provider VARCHAR(30) NOT NULL,
                    amount DECIMAL(12,2) NOT NULL,
                    currency VARCHAR(10) NOT NULL,
                    purpose VARCHAR(30) NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    provider_transaction_id VARCHAR(128),
                    payment_url TEXT,
                    callback_payload TEXT,
                    settlement_transaction_id BIGINT,
                    return_url TEXT,
                    ip_address VARCHAR(45),
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP,
                    expired_at TIMESTAMP,
                    CONSTRAINT uk_payment_orders_ref UNIQUE (payment_ref)
                )
                """);
    }

    private void createQueryIndexes(Connection connection) throws SQLException {
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_payment_ref ON payment_orders (payment_ref)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_payment_entity ON payment_orders (entity_id, entity_type)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_payment_status ON payment_orders (status)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_payment_provider ON payment_orders (provider)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_transactions_entity ON transactions (entity_id, entity_type)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_transactions_order ON transactions (order_id)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_transactions_status ON transactions (status)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_transactions_reason ON transactions (reason)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON transactions (created_at)");
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_transactions_entity_status
                ON transactions (entity_id, entity_type, status)
                """);
    }

    private void requireColumns(Connection connection, String tableName, Set<String> required,
                                String logicalName) throws SQLException {
        Set<String> columns = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData().getColumns(null, null, tableName, "%")) {
            while (resultSet.next()) {
                columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
            }
        }
        Set<String> missing = new HashSet<>(required);
        missing.removeAll(columns);
        if (!missing.isEmpty()) {
            throw new FlywayException("Existing " + logicalName + " table is missing core column(s): " + missing);
        }
    }

    private String findTable(Connection connection, String expectedName) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(null, null, "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(tableName)) {
                    return tableName;
                }
            }
        }
        return null;
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
