package db.migration;

import java.sql.Statement;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

public class V2__livestream_moderation_audit extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        try (Statement statement = context.getConnection().createStatement()) {
            statement.execute("""
                    CREATE TABLE livestream_moderation_audits (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        livestream_id UUID NOT NULL REFERENCES livestreams(id),
                        actor_principal_id BIGINT NOT NULL,
                        action VARCHAR(16) NOT NULL CHECK (action IN ('WARN', 'UNPIN', 'FORCE_END')),
                        reason VARCHAR(1000) NOT NULL CHECK (length(trim(reason)) > 0),
                        product_id BIGINT,
                        applied_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        CONSTRAINT ck_moderation_product_target CHECK (
                            (action = 'UNPIN' AND product_id IS NOT NULL AND product_id > 0)
                            OR (action <> 'UNPIN' AND product_id IS NULL))
                    )
                    """);
            statement.execute("CREATE INDEX idx_moderation_stream_applied ON livestream_moderation_audits (livestream_id, applied_at DESC)");
        }
    }
}
