package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Statement;

/** Stores the immutable result of an idempotent internal checkout handoff. */
public class V4__livestream_checkout_receipts extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        try (Statement statement = context.getConnection().createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS livestream_checkout_receipts (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        actor_principal_id BIGINT NOT NULL,
                        idempotency_key VARCHAR(255) NOT NULL,
                        request_fingerprint VARCHAR(64) NOT NULL,
                        context_payload TEXT NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        CONSTRAINT uk_livestream_checkout_receipt_actor_key
                            UNIQUE (actor_principal_id, idempotency_key)
                    )
                    """);
            statement.execute("CREATE INDEX IF NOT EXISTS idx_livestream_checkout_receipt_created "
                    + "ON livestream_checkout_receipts (created_at)");
        }
    }
}
