CREATE TABLE IF NOT EXISTS outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    event_key VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(16) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP NULL,
    last_error VARCHAR(2000) NULL,
    CONSTRAINT uk_delivery_outbox_event_id UNIQUE (event_id),
    CONSTRAINT ck_delivery_outbox_status CHECK (status IN ('PENDING', 'SENT', 'DEAD'))
);

ALTER TABLE outbox_events
    ADD COLUMN IF NOT EXISTS event_id UUID;
ALTER TABLE outbox_events
    ADD COLUMN IF NOT EXISTS aggregate_type VARCHAR(64);
ALTER TABLE outbox_events
    ADD COLUMN IF NOT EXISTS aggregate_id VARCHAR(255);
ALTER TABLE outbox_events
    ADD COLUMN IF NOT EXISTS event_type VARCHAR(128);
ALTER TABLE outbox_events
    ADD COLUMN IF NOT EXISTS attempts INTEGER;
ALTER TABLE outbox_events
    ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMP;
ALTER TABLE outbox_events
    ADD COLUMN IF NOT EXISTS last_error VARCHAR(2000);

UPDATE outbox_events
SET attempts = 0
WHERE attempts IS NULL;

UPDATE outbox_events
SET next_attempt_at = created_at
WHERE next_attempt_at IS NULL
  AND created_at IS NOT NULL;

UPDATE outbox_events
SET next_attempt_at = CURRENT_TIMESTAMP
WHERE next_attempt_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_delivery_outbox_pending
    ON outbox_events (status, next_attempt_at, created_at);
CREATE INDEX IF NOT EXISTS idx_delivery_outbox_aggregate
    ON outbox_events (aggregate_type, aggregate_id, created_at);
