#!/usr/bin/env python3
"""Audit resolved runtime TGF graphs generated by Maven dependency:tree.

Run a fresh reactor build, then Maven dependency:tree with -Dscope=runtime
-DoutputType=tgf -DoutputFile=target/phase8-runtime-dependencies.tgf first.
Source imports and provided dependencies remain covered by the static gate.
"""
import argparse
import importlib.util
from pathlib import Path

SPEC = importlib.util.spec_from_file_location(
    "module_boundaries", Path(__file__).with_name("verify-module-boundaries.py")
)
boundaries = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(boundaries)
GRAPH = "target/phase8-runtime-dependencies.tgf"


def read_graph(path: Path) -> list[tuple[str, str]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    separator = lines.index("#")
    nodes = {}
    for line in lines[:separator]:
        identity, coordinate = line.split(maxsplit=1)
        parts = coordinate.split(":")
        if len(parts) < 4 or identity in nodes:
            raise ValueError("invalid or duplicate Maven node")
        nodes[identity] = (parts[0], parts[1])
    if not nodes:
        raise ValueError("empty graph")
    edges = []
    for line in lines[separator + 1:]:
        if not line.strip():
            continue
        parts = line.split()
        if len(parts) < 2 or parts[0] not in nodes or parts[1] not in nodes:
            raise ValueError("edge references an absent node")
        edges.append((parts[0], parts[1]))
    incoming = {child for _, child in edges}
    roots = [node for node in nodes if node not in incoming]
    if len(roots) != 1 or roots[0] != next(iter(nodes)):
        raise ValueError("graph must have exactly one first/root node")
    reachable = {roots[0]}
    while True:
        expanded = reachable | {child for parent, child in edges if parent in reachable}
        if expanded == reachable:
            break
        reachable = expanded
    if len(reachable) != len(nodes):
        raise ValueError("disconnected dependency graph")
    return list(nodes.values())


def check_graph(path: Path, artifact: str, layer: str) -> list[str]:
    if not path.is_file():
        return [f"{path}: missing runtime dependency graph"]
    try:
        nodes = read_graph(path)
    except (OSError, ValueError) as error:
        return [f"{path}: invalid graph ({error})"]
    if nodes[0] != ("com.delivery", artifact):
        return [f"{path}: graph root does not match com.delivery:{artifact}"]
    kind = boundaries.core_kind(artifact)
    allowed = set()
    if kind is not None:
        service, _ = kind
        allowed = {"domain": set(), "application-api": {f"{service}-domain"},
                   "application": {f"{service}-domain", f"{service}-application-api"}}[layer]
    errors = []
    for group, dependency in nodes[1:]:
        if layer != "service" and group.startswith(boundaries.FORBIDDEN_CORE_GROUPS):
            errors.append(f"{path}: {layer} has resolved framework dependency {group}:{dependency}")
        if group == "com.delivery":
            if kind is not None and dependency not in allowed:
                errors.append(f"{path}: {layer} has resolved forbidden dependency {dependency}")
            elif dependency.endswith("-service") and dependency != artifact:
                errors.append(f"{path}: resolved dependency on foreign service implementation {dependency}")
    return errors


def inventory(root: Path) -> list[tuple[Path, str, str]]:
    candidates = [(path, "service") for path in boundaries.service_poms(root)]
    candidates += [(path, "contract") for path in root.glob("*-contracts/pom.xml")]
    candidates += [(path, "contract") for path in (root / "contracts").glob("*/pom.xml")]
    for path in boundaries.business_module_poms(root):
        artifact = boundaries.child_text(boundaries.parse_pom(path), "m:artifactId")
        kind = boundaries.core_kind(artifact)
        if kind is not None:
            candidates.append((path, kind[1]))
    return [(path.parent / GRAPH,
             boundaries.child_text(boundaries.parse_pom(path), "m:artifactId"), layer)
            for path, layer in sorted(candidates)]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    targets = inventory(args.root.resolve())
    errors = [error for path, artifact, layer in targets for error in check_graph(path, artifact, layer)]
    if not targets:
        errors.append("no service, contract or core module graphs found")
    if errors:
        print("Resolved runtime dependency audit FAILED")
        print("\n".join(f"- {error}" for error in errors))
        return 1
    print(f"Resolved runtime dependency audit PASSED: {len(targets)} module graphs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
