package db.migration;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/** Owns authentication account/session persistence and token identity constraints. */
public class V1__auth_schema extends BaseJavaMigration {

    private static final Set<String> ACCOUNT_COLUMNS = Set.of(
            "id", "user_id", "email", "password_hash", "role", "is_active",
            "created_at", "updated_at");
    private static final Set<String> SESSION_COLUMNS = Set.of(
            "id", "auth_id", "device_id", "device_name", "device_type", "ip_address",
            "refresh_token", "is_active", "last_login_at", "expires_at", "created_at");

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String accounts = findTable(connection, "auth_account");
        String sessions = findTable(connection, "auth_session");

        if (accounts == null && sessions == null) {
            createTables(connection);
            accounts = findTable(connection, "auth_account");
            sessions = findTable(connection, "auth_session");
        } else if (accounts == null || sessions == null) {
            throw new FlywayException("Existing Auth schema is incomplete: auth_account and auth_session must both exist");
        } else {
            requireColumns(connection, accounts, ACCOUNT_COLUMNS, "auth_account");
            requireColumns(connection, sessions, SESSION_COLUMNS, "auth_session");
        }

        requireNoDuplicate(connection, "auth_account", "email", false, "email");
        requireNoDuplicate(connection, "auth_session", "refresh_token", true, "refresh token");
        if (!hasUniqueSingleColumnIndex(connection, accounts, "email")) {
            execute(connection, "ALTER TABLE auth_account ADD CONSTRAINT uk_auth_account_email UNIQUE (email)");
        }
        if (!hasUniqueSingleColumnIndex(connection, sessions, "refresh_token")) {
            execute(connection, """
                    ALTER TABLE auth_session
                    ADD CONSTRAINT uk_auth_session_refresh_token UNIQUE (refresh_token)
                    """);
        }
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_auth_session_account_active_expiry
                ON auth_session (auth_id, is_active, expires_at, last_login_at)
                """);
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_auth_session_account_device_active
                ON auth_session (auth_id, device_id, is_active)
                """);
    }

    private void createTables(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE auth_account (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT,
                    email VARCHAR(255) NOT NULL,
                    password_hash VARCHAR(255) NOT NULL,
                    role VARCHAR(255) NOT NULL,
                    is_active BOOLEAN,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    CONSTRAINT uk_auth_account_email UNIQUE (email)
                )
                """);
        execute(connection, """
                CREATE TABLE auth_session (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    auth_id BIGINT NOT NULL,
                    device_id VARCHAR(255) NOT NULL,
                    device_name VARCHAR(255),
                    device_type VARCHAR(255),
                    ip_address VARCHAR(255),
                    refresh_token TEXT,
                    is_active BOOLEAN,
                    last_login_at TIMESTAMP,
                    expires_at TIMESTAMP,
                    created_at TIMESTAMP,
                    CONSTRAINT uk_auth_session_refresh_token UNIQUE (refresh_token),
                    CONSTRAINT fk_auth_session_account
                        FOREIGN KEY (auth_id) REFERENCES auth_account (id)
                )
                """);
    }

    private void requireNoDuplicate(Connection connection, String table, String column,
                                    boolean ignoreNull, String label) throws SQLException {
        String where = ignoreNull ? " WHERE " + column + " IS NOT NULL" : "";
        long duplicateGroups = queryCount(connection, "SELECT count(*) FROM (SELECT " + column
                + " FROM " + table + where + " GROUP BY " + column + " HAVING count(*) > 1) duplicates");
        if (duplicateGroups > 0) {
            throw new FlywayException("Auth schema contains " + duplicateGroups + " duplicate " + label
                    + " group(s); manual reconciliation is required");
        }
    }

    private void requireColumns(Connection connection, String tableName, Set<String> required,
                                String logicalName) throws SQLException {
        Set<String> columns = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData().getColumns(null, null, tableName, "%")) {
            while (resultSet.next()) {
                columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
            }
        }
        Set<String> missing = new HashSet<>(required);
        missing.removeAll(columns);
        if (!missing.isEmpty()) {
            throw new FlywayException("Existing " + logicalName + " table is missing core column(s): " + missing);
        }
    }

    private long queryCount(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private String findTable(Connection connection, String expectedName) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(null, null, "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(tableName)) {
                    return tableName;
                }
            }
        }
        return null;
    }

    private boolean hasUniqueSingleColumnIndex(Connection connection, String tableName, String columnName)
            throws SQLException {
        Map<String, Set<String>> columnsByIndex = new HashMap<>();
        try (ResultSet indexes = connection.getMetaData().getIndexInfo(null, null, tableName, true, false)) {
            while (indexes.next()) {
                String index = indexes.getString("INDEX_NAME");
                String column = indexes.getString("COLUMN_NAME");
                if (index != null && column != null) {
                    columnsByIndex.computeIfAbsent(index.toLowerCase(Locale.ROOT), ignored -> new HashSet<>())
                            .add(column.toLowerCase(Locale.ROOT));
                }
            }
        }
        return columnsByIndex.values().stream().anyMatch(columns -> columns.equals(Set.of(columnName)));
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
