CREATE TABLE shipper_location_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    delivery_id BIGINT NOT NULL,
    shipper_id BIGINT NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    latitude DECIMAL(8,5) NOT NULL,
    longitude DECIMAL(8,5) NOT NULL,
    accuracy DECIMAL(8,2),
    speed DECIMAL(8,2),
    heading DECIMAL(8,2),
    source VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_location_history_event UNIQUE (event_id)
);

CREATE INDEX idx_location_history_delivery_time
    ON shipper_location_history (delivery_id, occurred_at, id);
CREATE INDEX idx_location_history_shipper_time
    ON shipper_location_history (shipper_id, occurred_at, id);

CREATE TABLE location_history_receipts (
    event_id UUID PRIMARY KEY,
    delivery_id BIGINT,
    shipper_id BIGINT NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    outcome VARCHAR(32) NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_location_history_receipt_outcome CHECK (
        outcome IN ('PERSISTED', 'SAMPLED_OUT', 'NO_DELIVERY', 'OFFLINE_TOMBSTONE')
    )
);

CREATE INDEX idx_location_history_receipts_processed
    ON location_history_receipts (processed_at);
