package db.migration;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.HexFormat;
import java.util.Locale;
import java.util.UUID;

/** Adds one replay-detectable refresh-token family per device session. */
public class V3__refresh_token_families extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String sessions = findTable(connection, "auth_session");
        if (sessions == null) {
            throw new FlywayException("Auth refresh-token migration requires auth_session");
        }

        if (!hasColumn(connection, sessions, "token_family_id")) {
            execute(connection, "ALTER TABLE auth_session ADD COLUMN token_family_id VARCHAR(36)");
        }

        execute(connection, """
                CREATE TABLE IF NOT EXISTS auth_refresh_token (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    session_id BIGINT NOT NULL,
                    token_hash VARCHAR(64) NOT NULL,
                    state VARCHAR(16) NOT NULL,
                    issued_at TIMESTAMP NOT NULL,
                    expires_at TIMESTAMP NOT NULL,
                    rotated_at TIMESTAMP,
                    revoked_at TIMESTAMP,
                    CONSTRAINT uk_auth_refresh_token_hash UNIQUE (token_hash),
                    CONSTRAINT fk_auth_refresh_token_session
                        FOREIGN KEY (session_id) REFERENCES auth_session (id)
                )
                """);

        migrateLegacySessions(connection);
        execute(connection, "UPDATE auth_session SET refresh_token = NULL WHERE refresh_token IS NOT NULL");
        execute(connection, "ALTER TABLE auth_session ALTER COLUMN token_family_id SET NOT NULL");
        execute(connection, """
                CREATE UNIQUE INDEX IF NOT EXISTS uk_auth_session_token_family
                ON auth_session (token_family_id)
                """);
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_auth_refresh_token_session_state
                ON auth_refresh_token (session_id, state, id)
                """);
    }

    private void migrateLegacySessions(Connection connection) throws Exception {
        LocalDateTime now = LocalDateTime.now();
        try (PreparedStatement select = connection.prepareStatement("""
                SELECT id, token_family_id, refresh_token, is_active,
                       last_login_at, expires_at, created_at
                FROM auth_session ORDER BY id
                """);
             ResultSet rows = select.executeQuery();
             PreparedStatement updateFamily = connection.prepareStatement(
                     "UPDATE auth_session SET token_family_id = ? WHERE id = ?");
             PreparedStatement insertToken = connection.prepareStatement("""
                     INSERT INTO auth_refresh_token
                         (session_id, token_hash, state, issued_at, expires_at, revoked_at)
                     VALUES (?, ?, ?, ?, ?, ?)
                     """)) {
            while (rows.next()) {
                long sessionId = rows.getLong("id");
                String familyId = rows.getString("token_family_id");
                if (familyId == null || familyId.isBlank()) {
                    familyId = UUID.randomUUID().toString();
                    updateFamily.setString(1, familyId);
                    updateFamily.setLong(2, sessionId);
                    updateFamily.executeUpdate();
                }

                String rawToken = rows.getString("refresh_token");
                if (rawToken == null || rawToken.isBlank()) {
                    continue;
                }

                LocalDateTime expiresAt = timestamp(rows, "expires_at", now);
                boolean active = rows.getBoolean("is_active")
                        && !rows.wasNull()
                        && expiresAt.isAfter(now);
                LocalDateTime issuedAt = timestamp(rows, "last_login_at",
                        timestamp(rows, "created_at", now));

                insertToken.setLong(1, sessionId);
                insertToken.setString(2, sha256(rawToken));
                insertToken.setString(3, active ? "CURRENT" : "REVOKED");
                insertToken.setTimestamp(4, Timestamp.valueOf(issuedAt));
                insertToken.setTimestamp(5, Timestamp.valueOf(expiresAt));
                if (active) {
                    insertToken.setNull(6, java.sql.Types.TIMESTAMP);
                } else {
                    insertToken.setTimestamp(6, Timestamp.valueOf(now));
                }
                insertToken.executeUpdate();
            }
        }
    }

    private LocalDateTime timestamp(ResultSet rows, String column, LocalDateTime fallback)
            throws SQLException {
        Timestamp value = rows.getTimestamp(column);
        return value == null ? fallback : value.toLocalDateTime();
    }

    private String sha256(String token) throws Exception {
        byte[] digest = MessageDigest.getInstance("SHA-256")
                .digest(token.getBytes(StandardCharsets.UTF_8));
        return HexFormat.of().formatHex(digest);
    }

    private boolean hasColumn(Connection connection, String tableName, String expectedColumn)
            throws SQLException {
        try (ResultSet columns = connection.getMetaData().getColumns(null, null, tableName, "%")) {
            while (columns.next()) {
                if (expectedColumn.equalsIgnoreCase(columns.getString("COLUMN_NAME"))) {
                    return true;
                }
            }
        }
        return false;
    }

    private String findTable(Connection connection, String expectedName) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(null, null, "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(tableName)) {
                    return tableName.toLowerCase(Locale.ROOT);
                }
            }
        }
        return null;
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
