package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;

/** Adds account-bound one-time security tokens and token-free security audit records. */
public class V4__password_reset_email_verification extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String accounts = findTable(connection, "auth_account");
        if (accounts == null) return;

        addColumnIfMissing(connection, accounts, "email_verification_required", """
                ALTER TABLE auth_account
                ADD COLUMN email_verification_required BOOLEAN NOT NULL DEFAULT FALSE
                """);
        addColumnIfMissing(connection, accounts, "email_verified_at", """
                ALTER TABLE auth_account ADD COLUMN email_verified_at TIMESTAMP
                """);

        // Existing accounts keep their current login behavior. New password
        // registrations explicitly set verification_required=true in code.
        execute(connection, """
                UPDATE auth_account
                SET email_verified_at = COALESCE(created_at, CURRENT_TIMESTAMP),
                    email_verification_required = FALSE
                WHERE email_verified_at IS NULL
                """);

        execute(connection, """
                CREATE TABLE IF NOT EXISTS auth_security_token (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    auth_id BIGINT NOT NULL,
                    purpose VARCHAR(32) NOT NULL,
                    token_hash VARCHAR(64) NOT NULL,
                    expires_at TIMESTAMP NOT NULL,
                    consumed_at TIMESTAMP,
                    created_at TIMESTAMP NOT NULL,
                    CONSTRAINT uk_auth_security_token_hash UNIQUE (token_hash),
                    CONSTRAINT fk_auth_security_token_account
                        FOREIGN KEY (auth_id) REFERENCES auth_account (id)
                )
                """);
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_auth_security_token_account_purpose
                ON auth_security_token (auth_id, purpose, consumed_at, expires_at)
                """);
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_auth_security_token_expiry
                ON auth_security_token (expires_at)
                """);

        execute(connection, """
                CREATE TABLE IF NOT EXISTS auth_security_audit (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    auth_id BIGINT,
                    action VARCHAR(64) NOT NULL,
                    outcome VARCHAR(32) NOT NULL,
                    subject_hash VARCHAR(64),
                    client_ip_hash VARCHAR(64),
                    occurred_at TIMESTAMP NOT NULL
                )
                """);
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_auth_security_audit_time
                ON auth_security_audit (occurred_at, id)
                """);
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_auth_security_audit_account_time
                ON auth_security_audit (auth_id, occurred_at, id)
                """);
    }

    private void addColumnIfMissing(Connection connection, String table, String column, String sql)
            throws SQLException {
        if (!hasColumn(connection, table, column)) execute(connection, sql);
    }

    private boolean hasColumn(Connection connection, String table, String expected) throws SQLException {
        try (ResultSet columns = connection.getMetaData().getColumns(null, null, table, "%")) {
            while (columns.next()) {
                if (expected.equalsIgnoreCase(columns.getString("COLUMN_NAME"))) return true;
            }
        }
        return false;
    }

    private String findTable(Connection connection, String expected) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(null, null, "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String name = tables.getString("TABLE_NAME");
                if (expected.equalsIgnoreCase(name)) return name.toLowerCase(Locale.ROOT);
            }
        }
        return null;
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) { statement.execute(sql); }
    }
}
