package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.Statement;

/** Additive identity authority state. Legacy user_id remains until final drain. */
public class V5__identity_lifecycle_outbox extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        execute(connection, "ALTER TABLE auth_account ADD COLUMN IF NOT EXISTS lifecycle_status VARCHAR(64)");
        execute(connection, "ALTER TABLE auth_account ADD COLUMN IF NOT EXISTS lifecycle_version BIGINT NOT NULL DEFAULT 0");
        execute(connection, "UPDATE auth_account SET lifecycle_status = CASE "
                + "WHEN COALESCE(is_active, false) = false THEN 'BLOCKED' "
                + "WHEN user_id IS NULL THEN 'PENDING_PROFILE' "
                + "WHEN COALESCE(email_verification_required, false) = true AND email_verified_at IS NULL "
                + "THEN 'PENDING_EMAIL_VERIFICATION' ELSE 'ACTIVE' END "
                + "WHERE lifecycle_status IS NULL");
        execute(connection, "ALTER TABLE auth_account ALTER COLUMN lifecycle_status SET NOT NULL");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_auth_account_lifecycle ON auth_account (lifecycle_status, id)");
        execute(connection, "CREATE TABLE IF NOT EXISTS identity_outbox_events ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "event_id UUID NOT NULL UNIQUE,event_type VARCHAR(128) NOT NULL,"
                + "aggregate_id BIGINT NOT NULL,topic VARCHAR(255) NOT NULL,event_key VARCHAR(128) NOT NULL,"
                + "payload TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,available_at TIMESTAMP NOT NULL,"
                + "published_at TIMESTAMP,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_identity_outbox_pending "
                + "ON identity_outbox_events (published_at, available_at, id)");
        execute(connection, "CREATE TABLE IF NOT EXISTS identity_inbox_receipts ("
                + "event_id UUID PRIMARY KEY,event_type VARCHAR(128) NOT NULL,principal_id BIGINT NOT NULL,"
                + "payload_fingerprint VARCHAR(64) NOT NULL,processed_at TIMESTAMP NOT NULL)");
    }

    private void execute(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement()) { statement.execute(sql); }
    }
}
