package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;
import java.sql.Connection;
import java.sql.Statement;

public class V6__identity_registration_handles extends BaseJavaMigration {
    @Override public void migrate(Context context) throws Exception {
        try (Statement statement = context.getConnection().createStatement()) {
            statement.execute("CREATE TABLE IF NOT EXISTS identity_registrations ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "auth_account_id BIGINT NOT NULL,handle_hash VARCHAR(64) NOT NULL UNIQUE,"
                    + "expires_at TIMESTAMP NOT NULL,created_at TIMESTAMP NOT NULL,"
                    + "CONSTRAINT fk_identity_registration_account FOREIGN KEY (auth_account_id) REFERENCES auth_account(id))");
            statement.execute("CREATE INDEX IF NOT EXISTS idx_identity_registration_expiry ON identity_registrations (expires_at)");
        }
    }
}
