package db.migration;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/** Owns shipper identity, current-location and dormant rating persistence. */
public class V1__shipper_schema extends BaseJavaMigration {

    private static final Set<String> SHIPPER_COLUMNS = Set.of(
            "id", "user_id", "full_name", "vehicle_type", "license_number", "id_card", "phone",
            "driver_image", "id_card_front_image", "id_card_back_image", "license_image",
            "license_plate", "is_online", "rating", "completed_deliveries", "created_at", "updated_at");
    private static final Set<String> LOCATION_COLUMNS = Set.of(
            "id", "shipper_id", "lat", "lng", "updated_at");
    private static final Set<String> RATING_COLUMNS = Set.of(
            "id", "shipper_id", "customer_id", "order_id", "rating", "comment", "created_at");

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String shippers = findTable(connection, "shipper");
        String locations = findTable(connection, "shipper_locations");
        String ratings = findTable(connection, "shipper_ratings");
        int existing = (shippers == null ? 0 : 1) + (locations == null ? 0 : 1) + (ratings == null ? 0 : 1);

        if (existing == 0) {
            createTables(connection);
            shippers = findTable(connection, "shipper");
            locations = findTable(connection, "shipper_locations");
            ratings = findTable(connection, "shipper_ratings");
        } else if (existing != 3) {
            throw new FlywayException("Existing Shipper schema is incomplete: shipper, shipper_locations, "
                    + "and shipper_ratings must all exist");
        } else {
            addNullableColumnIfMissing(connection, shippers, "full_name", "full_name VARCHAR(100)");
            requireColumns(connection, shippers, SHIPPER_COLUMNS, "shipper");
            requireColumns(connection, locations, LOCATION_COLUMNS, "shipper_locations");
            requireColumns(connection, ratings, RATING_COLUMNS, "shipper_ratings");
        }

        requireNoDuplicate(connection, "shipper", "user_id", false, "user_id");
        requireNoDuplicate(connection, "shipper", "license_number", true, "license_number");
        requireNoDuplicate(connection, "shipper", "id_card", true, "id_card");
        requireNoDuplicate(connection, "shipper_locations", "shipper_id", false, "location shipper_id");
        requireNoDuplicate(connection, "shipper_ratings", "order_id", false, "rating order_id");
        addUniqueIfMissing(connection, shippers, "user_id", "uk_shipper_user_id");
        addUniqueIfMissing(connection, shippers, "license_number", "uk_shipper_license_number");
        addUniqueIfMissing(connection, shippers, "id_card", "uk_shipper_id_card");
        addUniqueIfMissing(connection, locations, "shipper_id", "uk_shipper_locations_shipper_id");
        addUniqueIfMissing(connection, ratings, "order_id", "uk_shipper_ratings_order_id");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_shipper_online ON shipper (is_online)");
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_shipper_ratings_shipper_created
                ON shipper_ratings (shipper_id, created_at)
                """);
    }

    private void createTables(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE shipper (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    full_name VARCHAR(100), vehicle_type VARCHAR(50), license_number VARCHAR(50),
                    id_card VARCHAR(20), phone VARCHAR(15), driver_image TEXT,
                    id_card_front_image TEXT, id_card_back_image TEXT, license_image TEXT,
                    license_plate VARCHAR(20), is_online BOOLEAN, rating DECIMAL(2,1),
                    completed_deliveries INTEGER, created_at TIMESTAMP, updated_at TIMESTAMP,
                    CONSTRAINT uk_shipper_user_id UNIQUE (user_id),
                    CONSTRAINT uk_shipper_license_number UNIQUE (license_number),
                    CONSTRAINT uk_shipper_id_card UNIQUE (id_card)
                )
                """);
        execute(connection, """
                CREATE TABLE shipper_locations (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    shipper_id BIGINT NOT NULL, lat DOUBLE PRECISION NOT NULL,
                    lng DOUBLE PRECISION NOT NULL, updated_at TIMESTAMP,
                    CONSTRAINT uk_shipper_locations_shipper_id UNIQUE (shipper_id)
                )
                """);
        execute(connection, """
                CREATE TABLE shipper_ratings (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    shipper_id BIGINT NOT NULL, customer_id BIGINT NOT NULL, order_id BIGINT NOT NULL,
                    rating INTEGER NOT NULL, comment TEXT, created_at TIMESTAMP,
                    CONSTRAINT uk_shipper_ratings_order_id UNIQUE (order_id)
                )
                """);
    }

    private void requireNoDuplicate(Connection connection, String table, String column,
                                    boolean ignoreNull, String label) throws SQLException {
        String where = ignoreNull ? " WHERE " + column + " IS NOT NULL" : "";
        long groups = queryCount(connection, "SELECT count(*) FROM (SELECT " + column + " FROM "
                + table + where + " GROUP BY " + column + " HAVING count(*) > 1) duplicates");
        if (groups > 0) {
            throw new FlywayException("Shipper schema contains " + groups + " duplicate " + label
                    + " group(s); manual reconciliation is required");
        }
    }

    private void addUniqueIfMissing(Connection connection, String tableName, String column,
                                    String constraint) throws SQLException {
        if (!hasUniqueSingleColumnIndex(connection, tableName, column)) {
            execute(connection, "ALTER TABLE " + tableName + " ADD CONSTRAINT " + constraint
                    + " UNIQUE (" + column + ")");
        }
    }

    private void requireColumns(Connection connection, String tableName, Set<String> required,
                                String logicalName) throws SQLException {
        Set<String> columns = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData()
                .getColumns(null, connection.getSchema(), tableName, "%")) {
            while (resultSet.next()) columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
        }
        Set<String> missing = new HashSet<>(required);
        missing.removeAll(columns);
        if (!missing.isEmpty()) {
            throw new FlywayException("Existing " + logicalName + " table is missing core column(s): " + missing);
        }
    }

    private void addNullableColumnIfMissing(Connection connection, String tableName, String columnName,
                                            String definition) throws SQLException {
        Set<String> columns = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData()
                .getColumns(null, connection.getSchema(), tableName, "%")) {
            while (resultSet.next()) columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
        }
        if (!columns.contains(columnName.toLowerCase(Locale.ROOT))) {
            execute(connection, "ALTER TABLE " + tableName + " ADD COLUMN " + definition);
        }
    }

    private long queryCount(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement(); ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private String findTable(Connection connection, String expectedName) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(
                null, connection.getSchema(), "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String name = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(name)) return name;
            }
        }
        return null;
    }

    private boolean hasUniqueSingleColumnIndex(Connection connection, String tableName, String columnName)
            throws SQLException {
        Map<String, Set<String>> columnsByIndex = new HashMap<>();
        try (ResultSet indexes = connection.getMetaData().getIndexInfo(
                null, connection.getSchema(), tableName, true, false)) {
            while (indexes.next()) {
                String index = indexes.getString("INDEX_NAME");
                String column = indexes.getString("COLUMN_NAME");
                if (index != null && column != null) {
                    columnsByIndex.computeIfAbsent(index.toLowerCase(Locale.ROOT), ignored -> new HashSet<>())
                            .add(column.toLowerCase(Locale.ROOT));
                }
            }
        }
        return columnsByIndex.values().stream().anyMatch(columns -> columns.equals(Set.of(columnName)));
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
