CREATE TABLE order_create_idempotency_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal_id BIGINT NOT NULL,
    idempotency_key UUID NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    fingerprint_version VARCHAR(16) NOT NULL,
    order_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_order_create_idempotency_principal_key UNIQUE (principal_id, idempotency_key)
);

CREATE INDEX idx_order_create_idempotency_created
    ON order_create_idempotency_receipts (created_at);
