package db.migration;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/** Owns user profile/address persistence and Auth provisioning identity. */
public class V1__user_schema extends BaseJavaMigration {

    private static final Set<String> USER_COLUMNS = Set.of(
            "id", "auth_id", "email", "role", "full_name", "phone", "dob", "avatar_url",
            "address", "is_active", "is_blocked", "blocked_at", "blocked_by", "block_reason",
            "created_at", "updated_at");
    private static final Set<String> ADDRESS_COLUMNS = Set.of(
            "id", "user_id", "label", "recipient_name", "phone_number", "address_line", "ward",
            "district", "city", "postal_code", "latitude", "longitude", "is_default",
            "created_at", "updated_at");

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String users = findTable(connection, "users");
        String addresses = findTable(connection, "user_addresses");

        if (users == null && addresses == null) {
            createTables(connection);
            users = findTable(connection, "users");
        } else if (users == null || addresses == null) {
            throw new FlywayException("Existing User schema is incomplete: users and user_addresses must both exist");
        } else {
            requireColumns(connection, users, USER_COLUMNS, "users");
            requireColumns(connection, addresses, ADDRESS_COLUMNS, "user_addresses");
        }

        requireNoDuplicateAuthIds(connection);
        requireNoDuplicateEmails(connection);
        requireNoDuplicateDefaultAddresses(connection);
        if (!hasUniqueSingleColumnIndex(connection, users, "auth_id")) {
            execute(connection, "ALTER TABLE users ADD CONSTRAINT uk_users_auth_id UNIQUE (auth_id)");
        }
        createCaseInsensitiveEmailUniqueness(connection);
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_users_role ON users (role)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_users_active_blocked ON users (is_active, is_blocked)");
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_user_addresses_user_created
                ON user_addresses (user_id, created_at)
                """);
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_user_addresses_user_default
                ON user_addresses (user_id, is_default)
                """);
    }

    private void createTables(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    auth_id BIGINT NOT NULL,
                    email VARCHAR(255) NOT NULL,
                    role VARCHAR(255) NOT NULL,
                    full_name VARCHAR(255),
                    phone VARCHAR(255),
                    dob DATE,
                    avatar_url VARCHAR(255),
                    address VARCHAR(255),
                    is_active BOOLEAN,
                    is_blocked BOOLEAN,
                    blocked_at TIMESTAMP,
                    blocked_by BIGINT,
                    block_reason TEXT,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    CONSTRAINT uk_users_auth_id UNIQUE (auth_id)
                )
                """);
        execute(connection, """
                CREATE TABLE user_addresses (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT,
                    label VARCHAR(255),
                    recipient_name VARCHAR(255),
                    phone_number VARCHAR(255),
                    address_line VARCHAR(255),
                    ward VARCHAR(255),
                    district VARCHAR(255),
                    city VARCHAR(255),
                    postal_code VARCHAR(255),
                    latitude DOUBLE PRECISION,
                    longitude DOUBLE PRECISION,
                    is_default BOOLEAN,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP
                )
                """);
    }

    private void requireNoDuplicateAuthIds(Connection connection) throws SQLException {
        long duplicates = queryCount(connection, """
                SELECT count(*) FROM (
                    SELECT auth_id FROM users GROUP BY auth_id HAVING count(*) > 1
                ) duplicate_auth_ids
                """);
        if (duplicates > 0) {
            throw new FlywayException("User schema contains " + duplicates
                    + " duplicate auth_id group(s); manual reconciliation is required");
        }
    }

    private void requireNoDuplicateEmails(Connection connection) throws SQLException {
        long duplicates = queryCount(connection, """
                SELECT count(*) FROM (
                    SELECT lower(email) FROM users GROUP BY lower(email) HAVING count(*) > 1
                ) duplicate_emails
                """);
        if (duplicates > 0) {
            throw new FlywayException("User schema contains " + duplicates
                    + " duplicate email group(s); manual reconciliation is required");
        }
    }

    private void createCaseInsensitiveEmailUniqueness(Connection connection) throws SQLException {
        if (connection.getMetaData().getDatabaseProductName().toLowerCase(Locale.ROOT).contains("h2")) {
            execute(connection, """
                    ALTER TABLE users ADD COLUMN IF NOT EXISTS email_normalized VARCHAR(255)
                    GENERATED ALWAYS AS (LOWER(email))
                    """);
            execute(connection, """
                    CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email_lower
                    ON users (email_normalized)
                    """);
            return;
        }
        execute(connection, "CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email_lower ON users (LOWER(email))");
    }

    private void requireNoDuplicateDefaultAddresses(Connection connection) throws SQLException {
        long duplicates = queryCount(connection, """
                SELECT count(*) FROM (
                    SELECT user_id FROM user_addresses
                    WHERE is_default = true
                    GROUP BY user_id HAVING count(*) > 1
                ) duplicate_defaults
                """);
        if (duplicates > 0) {
            throw new FlywayException("User schema contains " + duplicates
                    + " user(s) with multiple default addresses; manual reconciliation is required");
        }
    }

    private void requireColumns(Connection connection, String tableName, Set<String> required,
                                String logicalName) throws SQLException {
        Set<String> columns = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData()
                .getColumns(null, connection.getSchema(), tableName, "%")) {
            while (resultSet.next()) {
                columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
            }
        }
        Set<String> missing = new HashSet<>(required);
        missing.removeAll(columns);
        if (!missing.isEmpty()) {
            throw new FlywayException("Existing " + logicalName + " table is missing core column(s): " + missing);
        }
    }

    private long queryCount(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private String findTable(Connection connection, String expectedName) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(
                null, connection.getSchema(), "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(tableName)) return tableName;
            }
        }
        return null;
    }

    private boolean hasUniqueSingleColumnIndex(Connection connection, String tableName, String columnName)
            throws SQLException {
        Map<String, Set<String>> columnsByIndex = new HashMap<>();
        try (ResultSet indexes = connection.getMetaData().getIndexInfo(
                null, connection.getSchema(), tableName, true, false)) {
            while (indexes.next()) {
                String index = indexes.getString("INDEX_NAME");
                String column = indexes.getString("COLUMN_NAME");
                if (index != null && column != null) {
                    columnsByIndex.computeIfAbsent(index.toLowerCase(Locale.ROOT), ignored -> new HashSet<>())
                            .add(column.toLowerCase(Locale.ROOT));
                }
            }
        }
        return columnsByIndex.values().stream().anyMatch(columns -> columns.equals(Set.of(columnName)));
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
