package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.Statement;

/** principal_id is additive: it mirrors auth_id until the legacy naming drain. */
public class V2__identity_principal_outbox extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        execute(connection, "ALTER TABLE users ADD COLUMN IF NOT EXISTS principal_id BIGINT");
        execute(connection, "UPDATE users SET principal_id = auth_id WHERE principal_id IS NULL");
        execute(connection, "ALTER TABLE users ALTER COLUMN principal_id SET NOT NULL");
        execute(connection, "CREATE UNIQUE INDEX IF NOT EXISTS uk_users_principal_id ON users (principal_id)");
        execute(connection, "ALTER TABLE users ADD COLUMN IF NOT EXISTS identity_status VARCHAR(64) NOT NULL DEFAULT 'ACTIVE'");
        execute(connection, "ALTER TABLE users ADD COLUMN IF NOT EXISTS identity_status_version BIGINT NOT NULL DEFAULT 0");
        execute(connection, "CREATE TABLE IF NOT EXISTS identity_outbox_events ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "event_id UUID NOT NULL UNIQUE,event_type VARCHAR(128) NOT NULL,"
                + "aggregate_id BIGINT NOT NULL,topic VARCHAR(255) NOT NULL,event_key VARCHAR(128) NOT NULL,"
                + "payload TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,available_at TIMESTAMP NOT NULL,"
                + "published_at TIMESTAMP,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_user_identity_outbox_pending "
                + "ON identity_outbox_events (published_at, available_at, id)");
        execute(connection, "CREATE UNIQUE INDEX IF NOT EXISTS uk_user_identity_outbox_aggregate_type "
                + "ON identity_outbox_events (event_type, aggregate_id)");
        execute(connection, "CREATE TABLE IF NOT EXISTS identity_inbox_receipts ("
                + "event_id UUID PRIMARY KEY,event_type VARCHAR(128) NOT NULL,principal_id BIGINT NOT NULL,"
                + "payload_fingerprint VARCHAR(64) NOT NULL,processed_at TIMESTAMP NOT NULL)");
    }

    private void execute(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement()) { statement.execute(sql); }
    }
}
