CREATE TABLE flash_sale_reservations (
    reservation_id UUID PRIMARY KEY, order_id BIGINT NOT NULL, user_id BIGINT NOT NULL,
    restaurant_id BIGINT NOT NULL, state VARCHAR(32) NOT NULL, expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_flash_reservation_order UNIQUE (order_id),
    CONSTRAINT ck_flash_reservation_state CHECK (state IN ('RESERVED','COMMITTED','RELEASED','EXPIRED'))
);
CREATE TABLE flash_sale_reservation_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id UUID NOT NULL, flash_sale_item_id BIGINT NOT NULL, menu_item_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL, unit_price DECIMAL(38,2) NOT NULL,
    CONSTRAINT fk_flash_reservation_line_reservation FOREIGN KEY (reservation_id)
        REFERENCES flash_sale_reservations (reservation_id),
    CONSTRAINT fk_flash_reservation_line_item FOREIGN KEY (flash_sale_item_id)
        REFERENCES flash_sale_items (id),
    CONSTRAINT uk_flash_reservation_line_item UNIQUE (reservation_id, flash_sale_item_id),
    CONSTRAINT ck_flash_reservation_line_quantity CHECK (quantity > 0),
    CONSTRAINT ck_flash_reservation_line_price CHECK (unit_price > 0)
);
CREATE INDEX idx_flash_reservation_expiry ON flash_sale_reservations (state, expires_at);
CREATE INDEX idx_flash_reservation_line_item ON flash_sale_reservation_lines (flash_sale_item_id);
