package db.migration;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

/** Owns the Saga aggregate and step-history schema previously managed by Hibernate update. */
public class V2__saga_state_schema extends BaseJavaMigration {

    private static final Set<String> INSTANCE_CORE_COLUMNS = Set.of(
            "id", "saga_type", "order_id", "delivery_id", "shipper_id", "status",
            "payload", "created_at", "updated_at", "completed_at");
    private static final Set<String> STEP_CORE_COLUMNS = Set.of(
            "id", "saga_instance_id", "step_name", "event_type", "event_data", "executed_at");

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String instances = findTable(connection, "saga_instances");
        String steps = findTable(connection, "saga_steps");

        if (instances == null && steps == null) {
            createSagaTables(connection);
            instances = findTable(connection, "saga_instances");
        } else if (instances == null || steps == null) {
            throw new FlywayException("Existing Saga schema is incomplete: saga_instances and saga_steps must both exist");
        } else {
            requireColumns(connection, instances, INSTANCE_CORE_COLUMNS, "saga_instances");
            requireColumns(connection, steps, STEP_CORE_COLUMNS, "saga_steps");
            addVersionColumn(connection);
        }

        requireNoDuplicateOrders(connection);
        if (!hasUniqueSingleColumnIndex(connection, instances, "order_id")) {
            execute(connection, """
                    ALTER TABLE saga_instances
                    ADD CONSTRAINT uk_saga_instances_order_id UNIQUE (order_id)
                    """);
        }
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_saga_order_id ON saga_instances (order_id)");
        execute(connection, "CREATE INDEX IF NOT EXISTS idx_saga_status ON saga_instances (status)");
    }

    private void createSagaTables(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE saga_instances (
                    id UUID PRIMARY KEY,
                    version BIGINT NOT NULL DEFAULT 0,
                    saga_type VARCHAR(255) NOT NULL,
                    order_id BIGINT NOT NULL,
                    delivery_id BIGINT,
                    shipper_id BIGINT,
                    status VARCHAR(255) NOT NULL,
                    payload JSONB,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP,
                    completed_at TIMESTAMP
                )
                """);
        execute(connection, """
                CREATE TABLE saga_steps (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    saga_instance_id UUID NOT NULL,
                    step_name VARCHAR(255) NOT NULL,
                    event_type VARCHAR(255) NOT NULL,
                    event_data TEXT,
                    executed_at TIMESTAMP NOT NULL,
                    CONSTRAINT fk_saga_steps_instance
                        FOREIGN KEY (saga_instance_id) REFERENCES saga_instances (id)
                )
                """);
    }

    private void addVersionColumn(Connection connection) throws SQLException {
        execute(connection, "ALTER TABLE saga_instances ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0");
        execute(connection, "UPDATE saga_instances SET version = 0 WHERE version IS NULL");
        execute(connection, "ALTER TABLE saga_instances ALTER COLUMN version SET DEFAULT 0");
        execute(connection, "ALTER TABLE saga_instances ALTER COLUMN version SET NOT NULL");
    }

    private void requireNoDuplicateOrders(Connection connection) throws SQLException {
        long duplicates = queryCount(connection, """
                SELECT count(*)
                FROM (
                    SELECT order_id
                    FROM saga_instances
                    GROUP BY order_id
                    HAVING count(*) > 1
                ) duplicate_orders
                """);
        if (duplicates > 0) {
            throw new FlywayException("Saga schema contains " + duplicates
                    + " duplicate order_id group(s); manual reconciliation is required");
        }
    }

    private void requireColumns(Connection connection, String tableName, Set<String> required,
                                String logicalName) throws SQLException {
        Set<String> columns = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData().getColumns(null, null, tableName, "%")) {
            while (resultSet.next()) {
                columns.add(resultSet.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
            }
        }
        Set<String> missing = new HashSet<>(required);
        missing.removeAll(columns);
        if (!missing.isEmpty()) {
            throw new FlywayException("Existing " + logicalName + " table is missing core column(s): " + missing);
        }
    }

    private long queryCount(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private String findTable(Connection connection, String expectedName) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet tables = metadata.getTables(null, null, "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                if (expectedName.equalsIgnoreCase(tableName)) {
                    return tableName;
                }
            }
        }
        return null;
    }

    private boolean hasUniqueSingleColumnIndex(Connection connection, String tableName, String columnName)
            throws SQLException {
        try (ResultSet indexes = connection.getMetaData().getIndexInfo(null, null, tableName, true, false)) {
            while (indexes.next()) {
                String indexedColumn = indexes.getString("COLUMN_NAME");
                short position = indexes.getShort("ORDINAL_POSITION");
                if (position == 1 && indexedColumn != null && columnName.equalsIgnoreCase(indexedColumn)) {
                    return true;
                }
            }
        }
        return false;
    }
}
